// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: DummyReply.proto

package com.stupidbeauty.hxlauncher;

public final class DummyReplyProtos {
  private DummyReplyProtos() {}
  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistryLite registry) {
  }

  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistry registry) {
    registerAllExtensions(
        (com.google.protobuf.ExtensionRegistryLite) registry);
  }
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_com_stupidbeauty_hxlauncher_DummyReply_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_com_stupidbeauty_hxlauncher_DummyReply_fieldAccessorTable;

  public static com.google.protobuf.Descriptors.FileDescriptor
      getDescriptor() {
    return descriptor;
  }
  private static  com.google.protobuf.Descriptors.FileDescriptor
      descriptor;
  static {
    java.lang.String[] descriptorData = {
      "\n\020DummyReply.proto\022\033com.stupidbeauty.hxl" +
      "auncher\032\021ReplyHeader.proto\"F\n\nDummyReply" +
      "\0228\n\006header\030\001 \001(\0132(.com.stupidbeauty.hxla" +
      "uncher.ReplyHeaderB1\n\033com.stupidbeauty.h" +
      "xlauncherB\020DummyReplyProtosP\001b\006proto3"
    };
    descriptor = com.google.protobuf.Descriptors.FileDescriptor
      .internalBuildGeneratedFileFrom(descriptorData,
        new com.google.protobuf.Descriptors.FileDescriptor[] {
          com.stupidbeauty.hxlauncher.ReplyHeaderProtos.getDescriptor(),
        });
    internal_static_com_stupidbeauty_hxlauncher_DummyReply_descriptor =
      getDescriptor().getMessageTypes().get(0);
    internal_static_com_stupidbeauty_hxlauncher_DummyReply_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_com_stupidbeauty_hxlauncher_DummyReply_descriptor,
        new java.lang.String[] { "Header", });
    com.stupidbeauty.hxlauncher.ReplyHeaderProtos.getDescriptor();
  }

  // @@protoc_insertion_point(outer_class_scope)
}
