// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: ExecutePhenemSequenceReq.proto

package com.stupidbeauty.hxlauncher;

public interface ExecutePhenemSequenceReqOrBuilder extends
    // @@protoc_insertion_point(interface_extends:com.stupidbeauty.hxlauncher.ExecutePhenemSequenceReq)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <pre>
   *当前的播放位置。
   * </pre>
   *
   * <code>int64 playing_position = 2;</code>
   */
  long getPlayingPosition();

  /**
   * <pre>
   *身体动作。
   * </pre>
   *
   * <code>string bodyAction = 3;</code>
   */
  java.lang.String getBodyAction();
  /**
   * <pre>
   *身体动作。
   * </pre>
   *
   * <code>string bodyAction = 3;</code>
   */
  com.google.protobuf.ByteString
      getBodyActionBytes();
}
