// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: ExecutePhenemSequenceReq.proto

package com.stupidbeauty.hxlauncher;

public final class ExecutePhenemSequenceReqProtos {
  private ExecutePhenemSequenceReqProtos() {}
  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistryLite registry) {
  }

  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistry registry) {
    registerAllExtensions(
        (com.google.protobuf.ExtensionRegistryLite) registry);
  }
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_com_stupidbeauty_hxlauncher_ExecutePhenemSequenceReq_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_com_stupidbeauty_hxlauncher_ExecutePhenemSequenceReq_fieldAccessorTable;

  public static com.google.protobuf.Descriptors.FileDescriptor
      getDescriptor() {
    return descriptor;
  }
  private static  com.google.protobuf.Descriptors.FileDescriptor
      descriptor;
  static {
    java.lang.String[] descriptorData = {
      "\n\036ExecutePhenemSequenceReq.proto\022\033com.st" +
      "upidbeauty.hxlauncher\"H\n\030ExecutePhenemSe" +
      "quenceReq\022\030\n\020playing_position\030\002 \001(\003\022\022\n\nb" +
      "odyAction\030\003 \001(\tB?\n\033com.stupidbeauty.hxla" +
      "uncherB\036ExecutePhenemSequenceReqProtosP\001" +
      "b\006proto3"
    };
    com.google.protobuf.Descriptors.FileDescriptor.InternalDescriptorAssigner assigner =
        new com.google.protobuf.Descriptors.FileDescriptor.    InternalDescriptorAssigner() {
          public com.google.protobuf.ExtensionRegistry assignDescriptors(
              com.google.protobuf.Descriptors.FileDescriptor root) {
            descriptor = root;
            return null;
          }
        };
    com.google.protobuf.Descriptors.FileDescriptor
      .internalBuildGeneratedFileFrom(descriptorData,
        new com.google.protobuf.Descriptors.FileDescriptor[] {
        }, assigner);
    internal_static_com_stupidbeauty_hxlauncher_ExecutePhenemSequenceReq_descriptor =
      getDescriptor().getMessageTypes().get(0);
    internal_static_com_stupidbeauty_hxlauncher_ExecutePhenemSequenceReq_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_com_stupidbeauty_hxlauncher_ExecutePhenemSequenceReq_descriptor,
        new java.lang.String[] { "PlayingPosition", "BodyAction", });
  }

  // @@protoc_insertion_point(outer_class_scope)
}
