// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: ExecutePhenemSequenceReq.proto

package com.stupidbeauty.hxlauncher;

/**
 * Protobuf type {@code com.stupidbeauty.hxlauncher.ExecutePhenemSequenceReq}
 */
public  final class ExecutePhenemSequenceReq extends
    com.google.protobuf.GeneratedMessageV3 implements
    // @@protoc_insertion_point(message_implements:com.stupidbeauty.hxlauncher.ExecutePhenemSequenceReq)
    ExecutePhenemSequenceReqOrBuilder {
private static final long serialVersionUID = 0L;
  // Use ExecutePhenemSequenceReq.newBuilder() to construct.
  private ExecutePhenemSequenceReq(com.google.protobuf.GeneratedMessageV3.Builder<?> builder) {
    super(builder);
  }
  private ExecutePhenemSequenceReq() {
    playingPosition_ = 0L;
    bodyAction_ = "";
  }

  @java.lang.Override
  public final com.google.protobuf.UnknownFieldSet
  getUnknownFields() {
    return this.unknownFields;
  }
  private ExecutePhenemSequenceReq(
      com.google.protobuf.CodedInputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    this();
    if (extensionRegistry == null) {
      throw new java.lang.NullPointerException();
    }
    int mutable_bitField0_ = 0;
    com.google.protobuf.UnknownFieldSet.Builder unknownFields =
        com.google.protobuf.UnknownFieldSet.newBuilder();
    try {
      boolean done = false;
      while (!done) {
        int tag = input.readTag();
        switch (tag) {
          case 0:
            done = true;
            break;
          case 16: {

            playingPosition_ = input.readInt64();
            break;
          }
          case 26: {
            java.lang.String s = input.readStringRequireUtf8();

            bodyAction_ = s;
            break;
          }
          default: {
            if (!parseUnknownFieldProto3(
                input, unknownFields, extensionRegistry, tag)) {
              done = true;
            }
            break;
          }
        }
      }
    } catch (com.google.protobuf.InvalidProtocolBufferException e) {
      throw e.setUnfinishedMessage(this);
    } catch (java.io.IOException e) {
      throw new com.google.protobuf.InvalidProtocolBufferException(
          e).setUnfinishedMessage(this);
    } finally {
      this.unknownFields = unknownFields.build();
      makeExtensionsImmutable();
    }
  }
  public static final com.google.protobuf.Descriptors.Descriptor
      getDescriptor() {
    return com.stupidbeauty.hxlauncher.ExecutePhenemSequenceReqProtos.internal_static_com_stupidbeauty_hxlauncher_ExecutePhenemSequenceReq_descriptor;
  }

  @java.lang.Override
  protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internalGetFieldAccessorTable() {
    return com.stupidbeauty.hxlauncher.ExecutePhenemSequenceReqProtos.internal_static_com_stupidbeauty_hxlauncher_ExecutePhenemSequenceReq_fieldAccessorTable
        .ensureFieldAccessorsInitialized(
            com.stupidbeauty.hxlauncher.ExecutePhenemSequenceReq.class, com.stupidbeauty.hxlauncher.ExecutePhenemSequenceReq.Builder.class);
  }

  public static final int PLAYING_POSITION_FIELD_NUMBER = 2;
  private long playingPosition_;
  /**
   * <pre>
   *当前的播放位置。
   * </pre>
   *
   * <code>int64 playing_position = 2;</code>
   */
  public long getPlayingPosition() {
    return playingPosition_;
  }

  public static final int BODYACTION_FIELD_NUMBER = 3;
  private volatile java.lang.Object bodyAction_;
  /**
   * <pre>
   *身体动作。
   * </pre>
   *
   * <code>string bodyAction = 3;</code>
   */
  public java.lang.String getBodyAction() {
    java.lang.Object ref = bodyAction_;
    if (ref instanceof java.lang.String) {
      return (java.lang.String) ref;
    } else {
      com.google.protobuf.ByteString bs = 
          (com.google.protobuf.ByteString) ref;
      java.lang.String s = bs.toStringUtf8();
      bodyAction_ = s;
      return s;
    }
  }
  /**
   * <pre>
   *身体动作。
   * </pre>
   *
   * <code>string bodyAction = 3;</code>
   */
  public com.google.protobuf.ByteString
      getBodyActionBytes() {
    java.lang.Object ref = bodyAction_;
    if (ref instanceof java.lang.String) {
      com.google.protobuf.ByteString b = 
          com.google.protobuf.ByteString.copyFromUtf8(
              (java.lang.String) ref);
      bodyAction_ = b;
      return b;
    } else {
      return (com.google.protobuf.ByteString) ref;
    }
  }

  private byte memoizedIsInitialized = -1;
  @java.lang.Override
  public final boolean isInitialized() {
    byte isInitialized = memoizedIsInitialized;
    if (isInitialized == 1) return true;
    if (isInitialized == 0) return false;

    memoizedIsInitialized = 1;
    return true;
  }

  @java.lang.Override
  public void writeTo(com.google.protobuf.CodedOutputStream output)
                      throws java.io.IOException {
    if (playingPosition_ != 0L) {
      output.writeInt64(2, playingPosition_);
    }
    if (!getBodyActionBytes().isEmpty()) {
      com.google.protobuf.GeneratedMessageV3.writeString(output, 3, bodyAction_);
    }
    unknownFields.writeTo(output);
  }

  @java.lang.Override
  public int getSerializedSize() {
    int size = memoizedSize;
    if (size != -1) return size;

    size = 0;
    if (playingPosition_ != 0L) {
      size += com.google.protobuf.CodedOutputStream
        .computeInt64Size(2, playingPosition_);
    }
    if (!getBodyActionBytes().isEmpty()) {
      size += com.google.protobuf.GeneratedMessageV3.computeStringSize(3, bodyAction_);
    }
    size += unknownFields.getSerializedSize();
    memoizedSize = size;
    return size;
  }

  @java.lang.Override
  public boolean equals(final java.lang.Object obj) {
    if (obj == this) {
     return true;
    }
    if (!(obj instanceof com.stupidbeauty.hxlauncher.ExecutePhenemSequenceReq)) {
      return super.equals(obj);
    }
    com.stupidbeauty.hxlauncher.ExecutePhenemSequenceReq other = (com.stupidbeauty.hxlauncher.ExecutePhenemSequenceReq) obj;

    boolean result = true;
    result = result && (getPlayingPosition()
        == other.getPlayingPosition());
    result = result && getBodyAction()
        .equals(other.getBodyAction());
    result = result && unknownFields.equals(other.unknownFields);
    return result;
  }

  @java.lang.Override
  public int hashCode() {
    if (memoizedHashCode != 0) {
      return memoizedHashCode;
    }
    int hash = 41;
    hash = (19 * hash) + getDescriptor().hashCode();
    hash = (37 * hash) + PLAYING_POSITION_FIELD_NUMBER;
    hash = (53 * hash) + com.google.protobuf.Internal.hashLong(
        getPlayingPosition());
    hash = (37 * hash) + BODYACTION_FIELD_NUMBER;
    hash = (53 * hash) + getBodyAction().hashCode();
    hash = (29 * hash) + unknownFields.hashCode();
    memoizedHashCode = hash;
    return hash;
  }

  public static com.stupidbeauty.hxlauncher.ExecutePhenemSequenceReq parseFrom(
      java.nio.ByteBuffer data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static com.stupidbeauty.hxlauncher.ExecutePhenemSequenceReq parseFrom(
      java.nio.ByteBuffer data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static com.stupidbeauty.hxlauncher.ExecutePhenemSequenceReq parseFrom(
      com.google.protobuf.ByteString data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static com.stupidbeauty.hxlauncher.ExecutePhenemSequenceReq parseFrom(
      com.google.protobuf.ByteString data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static com.stupidbeauty.hxlauncher.ExecutePhenemSequenceReq parseFrom(byte[] data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static com.stupidbeauty.hxlauncher.ExecutePhenemSequenceReq parseFrom(
      byte[] data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static com.stupidbeauty.hxlauncher.ExecutePhenemSequenceReq parseFrom(java.io.InputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input);
  }
  public static com.stupidbeauty.hxlauncher.ExecutePhenemSequenceReq parseFrom(
      java.io.InputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input, extensionRegistry);
  }
  public static com.stupidbeauty.hxlauncher.ExecutePhenemSequenceReq parseDelimitedFrom(java.io.InputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseDelimitedWithIOException(PARSER, input);
  }
  public static com.stupidbeauty.hxlauncher.ExecutePhenemSequenceReq parseDelimitedFrom(
      java.io.InputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseDelimitedWithIOException(PARSER, input, extensionRegistry);
  }
  public static com.stupidbeauty.hxlauncher.ExecutePhenemSequenceReq parseFrom(
      com.google.protobuf.CodedInputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input);
  }
  public static com.stupidbeauty.hxlauncher.ExecutePhenemSequenceReq parseFrom(
      com.google.protobuf.CodedInputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input, extensionRegistry);
  }

  @java.lang.Override
  public Builder newBuilderForType() { return newBuilder(); }
  public static Builder newBuilder() {
    return DEFAULT_INSTANCE.toBuilder();
  }
  public static Builder newBuilder(com.stupidbeauty.hxlauncher.ExecutePhenemSequenceReq prototype) {
    return DEFAULT_INSTANCE.toBuilder().mergeFrom(prototype);
  }
  @java.lang.Override
  public Builder toBuilder() {
    return this == DEFAULT_INSTANCE
        ? new Builder() : new Builder().mergeFrom(this);
  }

  @java.lang.Override
  protected Builder newBuilderForType(
      com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
    Builder builder = new Builder(parent);
    return builder;
  }
  /**
   * Protobuf type {@code com.stupidbeauty.hxlauncher.ExecutePhenemSequenceReq}
   */
  public static final class Builder extends
      com.google.protobuf.GeneratedMessageV3.Builder<Builder> implements
      // @@protoc_insertion_point(builder_implements:com.stupidbeauty.hxlauncher.ExecutePhenemSequenceReq)
      com.stupidbeauty.hxlauncher.ExecutePhenemSequenceReqOrBuilder {
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return com.stupidbeauty.hxlauncher.ExecutePhenemSequenceReqProtos.internal_static_com_stupidbeauty_hxlauncher_ExecutePhenemSequenceReq_descriptor;
    }

    @java.lang.Override
    protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return com.stupidbeauty.hxlauncher.ExecutePhenemSequenceReqProtos.internal_static_com_stupidbeauty_hxlauncher_ExecutePhenemSequenceReq_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              com.stupidbeauty.hxlauncher.ExecutePhenemSequenceReq.class, com.stupidbeauty.hxlauncher.ExecutePhenemSequenceReq.Builder.class);
    }

    // Construct using com.stupidbeauty.hxlauncher.ExecutePhenemSequenceReq.newBuilder()
    private Builder() {
      maybeForceBuilderInitialization();
    }

    private Builder(
        com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
      super(parent);
      maybeForceBuilderInitialization();
    }
    private void maybeForceBuilderInitialization() {
      if (com.google.protobuf.GeneratedMessageV3
              .alwaysUseFieldBuilders) {
      }
    }
    @java.lang.Override
    public Builder clear() {
      super.clear();
      playingPosition_ = 0L;

      bodyAction_ = "";

      return this;
    }

    @java.lang.Override
    public com.google.protobuf.Descriptors.Descriptor
        getDescriptorForType() {
      return com.stupidbeauty.hxlauncher.ExecutePhenemSequenceReqProtos.internal_static_com_stupidbeauty_hxlauncher_ExecutePhenemSequenceReq_descriptor;
    }

    @java.lang.Override
    public com.stupidbeauty.hxlauncher.ExecutePhenemSequenceReq getDefaultInstanceForType() {
      return com.stupidbeauty.hxlauncher.ExecutePhenemSequenceReq.getDefaultInstance();
    }

    @java.lang.Override
    public com.stupidbeauty.hxlauncher.ExecutePhenemSequenceReq build() {
      com.stupidbeauty.hxlauncher.ExecutePhenemSequenceReq result = buildPartial();
      if (!result.isInitialized()) {
        throw newUninitializedMessageException(result);
      }
      return result;
    }

    @java.lang.Override
    public com.stupidbeauty.hxlauncher.ExecutePhenemSequenceReq buildPartial() {
      com.stupidbeauty.hxlauncher.ExecutePhenemSequenceReq result = new com.stupidbeauty.hxlauncher.ExecutePhenemSequenceReq(this);
      result.playingPosition_ = playingPosition_;
      result.bodyAction_ = bodyAction_;
      onBuilt();
      return result;
    }

    @java.lang.Override
    public Builder clone() {
      return (Builder) super.clone();
    }
    @java.lang.Override
    public Builder setField(
        com.google.protobuf.Descriptors.FieldDescriptor field,
        java.lang.Object value) {
      return (Builder) super.setField(field, value);
    }
    @java.lang.Override
    public Builder clearField(
        com.google.protobuf.Descriptors.FieldDescriptor field) {
      return (Builder) super.clearField(field);
    }
    @java.lang.Override
    public Builder clearOneof(
        com.google.protobuf.Descriptors.OneofDescriptor oneof) {
      return (Builder) super.clearOneof(oneof);
    }
    @java.lang.Override
    public Builder setRepeatedField(
        com.google.protobuf.Descriptors.FieldDescriptor field,
        int index, java.lang.Object value) {
      return (Builder) super.setRepeatedField(field, index, value);
    }
    @java.lang.Override
    public Builder addRepeatedField(
        com.google.protobuf.Descriptors.FieldDescriptor field,
        java.lang.Object value) {
      return (Builder) super.addRepeatedField(field, value);
    }
    @java.lang.Override
    public Builder mergeFrom(com.google.protobuf.Message other) {
      if (other instanceof com.stupidbeauty.hxlauncher.ExecutePhenemSequenceReq) {
        return mergeFrom((com.stupidbeauty.hxlauncher.ExecutePhenemSequenceReq)other);
      } else {
        super.mergeFrom(other);
        return this;
      }
    }

    public Builder mergeFrom(com.stupidbeauty.hxlauncher.ExecutePhenemSequenceReq other) {
      if (other == com.stupidbeauty.hxlauncher.ExecutePhenemSequenceReq.getDefaultInstance()) return this;
      if (other.getPlayingPosition() != 0L) {
        setPlayingPosition(other.getPlayingPosition());
      }
      if (!other.getBodyAction().isEmpty()) {
        bodyAction_ = other.bodyAction_;
        onChanged();
      }
      this.mergeUnknownFields(other.unknownFields);
      onChanged();
      return this;
    }

    @java.lang.Override
    public final boolean isInitialized() {
      return true;
    }

    @java.lang.Override
    public Builder mergeFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      com.stupidbeauty.hxlauncher.ExecutePhenemSequenceReq parsedMessage = null;
      try {
        parsedMessage = PARSER.parsePartialFrom(input, extensionRegistry);
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        parsedMessage = (com.stupidbeauty.hxlauncher.ExecutePhenemSequenceReq) e.getUnfinishedMessage();
        throw e.unwrapIOException();
      } finally {
        if (parsedMessage != null) {
          mergeFrom(parsedMessage);
        }
      }
      return this;
    }

    private long playingPosition_ ;
    /**
     * <pre>
     *当前的播放位置。
     * </pre>
     *
     * <code>int64 playing_position = 2;</code>
     */
    public long getPlayingPosition() {
      return playingPosition_;
    }
    /**
     * <pre>
     *当前的播放位置。
     * </pre>
     *
     * <code>int64 playing_position = 2;</code>
     */
    public Builder setPlayingPosition(long value) {
      
      playingPosition_ = value;
      onChanged();
      return this;
    }
    /**
     * <pre>
     *当前的播放位置。
     * </pre>
     *
     * <code>int64 playing_position = 2;</code>
     */
    public Builder clearPlayingPosition() {
      
      playingPosition_ = 0L;
      onChanged();
      return this;
    }

    private java.lang.Object bodyAction_ = "";
    /**
     * <pre>
     *身体动作。
     * </pre>
     *
     * <code>string bodyAction = 3;</code>
     */
    public java.lang.String getBodyAction() {
      java.lang.Object ref = bodyAction_;
      if (!(ref instanceof java.lang.String)) {
        com.google.protobuf.ByteString bs =
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        bodyAction_ = s;
        return s;
      } else {
        return (java.lang.String) ref;
      }
    }
    /**
     * <pre>
     *身体动作。
     * </pre>
     *
     * <code>string bodyAction = 3;</code>
     */
    public com.google.protobuf.ByteString
        getBodyActionBytes() {
      java.lang.Object ref = bodyAction_;
      if (ref instanceof String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        bodyAction_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }
    /**
     * <pre>
     *身体动作。
     * </pre>
     *
     * <code>string bodyAction = 3;</code>
     */
    public Builder setBodyAction(
        java.lang.String value) {
      if (value == null) {
    throw new NullPointerException();
  }
  
      bodyAction_ = value;
      onChanged();
      return this;
    }
    /**
     * <pre>
     *身体动作。
     * </pre>
     *
     * <code>string bodyAction = 3;</code>
     */
    public Builder clearBodyAction() {
      
      bodyAction_ = getDefaultInstance().getBodyAction();
      onChanged();
      return this;
    }
    /**
     * <pre>
     *身体动作。
     * </pre>
     *
     * <code>string bodyAction = 3;</code>
     */
    public Builder setBodyActionBytes(
        com.google.protobuf.ByteString value) {
      if (value == null) {
    throw new NullPointerException();
  }
  checkByteStringIsUtf8(value);
      
      bodyAction_ = value;
      onChanged();
      return this;
    }
    @java.lang.Override
    public final Builder setUnknownFields(
        final com.google.protobuf.UnknownFieldSet unknownFields) {
      return super.setUnknownFieldsProto3(unknownFields);
    }

    @java.lang.Override
    public final Builder mergeUnknownFields(
        final com.google.protobuf.UnknownFieldSet unknownFields) {
      return super.mergeUnknownFields(unknownFields);
    }


    // @@protoc_insertion_point(builder_scope:com.stupidbeauty.hxlauncher.ExecutePhenemSequenceReq)
  }

  // @@protoc_insertion_point(class_scope:com.stupidbeauty.hxlauncher.ExecutePhenemSequenceReq)
  private static final com.stupidbeauty.hxlauncher.ExecutePhenemSequenceReq DEFAULT_INSTANCE;
  static {
    DEFAULT_INSTANCE = new com.stupidbeauty.hxlauncher.ExecutePhenemSequenceReq();
  }

  public static com.stupidbeauty.hxlauncher.ExecutePhenemSequenceReq getDefaultInstance() {
    return DEFAULT_INSTANCE;
  }

  private static final com.google.protobuf.Parser<ExecutePhenemSequenceReq>
      PARSER = new com.google.protobuf.AbstractParser<ExecutePhenemSequenceReq>() {
    @java.lang.Override
    public ExecutePhenemSequenceReq parsePartialFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return new ExecutePhenemSequenceReq(input, extensionRegistry);
    }
  };

  public static com.google.protobuf.Parser<ExecutePhenemSequenceReq> parser() {
    return PARSER;
  }

  @java.lang.Override
  public com.google.protobuf.Parser<ExecutePhenemSequenceReq> getParserForType() {
    return PARSER;
  }

  @java.lang.Override
  public com.stupidbeauty.hxlauncher.ExecutePhenemSequenceReq getDefaultInstanceForType() {
    return DEFAULT_INSTANCE;
  }

}

