// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: FileMessage.proto

package com.stupidbeauty.hxlauncher;

public final class FileMessageOuterClass {
  private FileMessageOuterClass() {}
  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistryLite registry) {
  }

  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistry registry) {
    registerAllExtensions(
        (com.google.protobuf.ExtensionRegistryLite) registry);
  }
  public interface FileMessageOrBuilder extends
      // @@protoc_insertion_point(interface_extends:com.stupidbeauty.hxlauncher.FileMessage)
      com.google.protobuf.MessageOrBuilder {

    /**
     * <pre>
     *文件或目录名字。
     * </pre>
     *
     * <code>string name = 1;</code>
     * @return The name.
     */
    java.lang.String getName();
    /**
     * <pre>
     *文件或目录名字。
     * </pre>
     *
     * <code>string name = 1;</code>
     * @return The bytes for name.
     */
    com.google.protobuf.ByteString
        getNameBytes();

    /**
     * <pre>
     *子文件或目录列表。
     * </pre>
     *
     * <code>repeated .com.stupidbeauty.hxlauncher.FileMessage sub_files = 2;</code>
     */
    java.util.List<com.stupidbeauty.hxlauncher.FileMessageOuterClass.FileMessage> 
        getSubFilesList();
    /**
     * <pre>
     *子文件或目录列表。
     * </pre>
     *
     * <code>repeated .com.stupidbeauty.hxlauncher.FileMessage sub_files = 2;</code>
     */
    com.stupidbeauty.hxlauncher.FileMessageOuterClass.FileMessage getSubFiles(int index);
    /**
     * <pre>
     *子文件或目录列表。
     * </pre>
     *
     * <code>repeated .com.stupidbeauty.hxlauncher.FileMessage sub_files = 2;</code>
     */
    int getSubFilesCount();
    /**
     * <pre>
     *子文件或目录列表。
     * </pre>
     *
     * <code>repeated .com.stupidbeauty.hxlauncher.FileMessage sub_files = 2;</code>
     */
    java.util.List<? extends com.stupidbeauty.hxlauncher.FileMessageOuterClass.FileMessageOrBuilder> 
        getSubFilesOrBuilderList();
    /**
     * <pre>
     *子文件或目录列表。
     * </pre>
     *
     * <code>repeated .com.stupidbeauty.hxlauncher.FileMessage sub_files = 2;</code>
     */
    com.stupidbeauty.hxlauncher.FileMessageOuterClass.FileMessageOrBuilder getSubFilesOrBuilder(
        int index);

    /**
     * <pre>
     *是否是文件。
     * </pre>
     *
     * <code>bool is_file = 3;</code>
     * @return The isFile.
     */
    boolean getIsFile();

    /**
     * <pre>
     *文件内容。
     * </pre>
     *
     * <code>bytes file_content = 4;</code>
     * @return The fileContent.
     */
    com.google.protobuf.ByteString getFileContent();

    /**
     * <pre>
     *这个文件的内容在victoriafreshdata大文件中的起始位置。
     * </pre>
     *
     * <code>int32 file_start_index = 5;</code>
     * @return The fileStartIndex.
     */
    int getFileStartIndex();

    /**
     * <pre>
     *这个文件的内容的长度。
     * </pre>
     *
     * <code>int32 file_length = 6;</code>
     * @return The fileLength.
     */
    int getFileLength();

    /**
     * <pre>
     *!&lt;文件内容是否被压缩了
     * </pre>
     *
     * <code>bool isCompressed = 7;</code>
     * @return The isCompressed.
     */
    boolean getIsCompressed();
  }
  /**
   * Protobuf type {@code com.stupidbeauty.hxlauncher.FileMessage}
   */
  public  static final class FileMessage extends
      com.google.protobuf.GeneratedMessageV3 implements
      // @@protoc_insertion_point(message_implements:com.stupidbeauty.hxlauncher.FileMessage)
      FileMessageOrBuilder {
  private static final long serialVersionUID = 0L;
    // Use FileMessage.newBuilder() to construct.
    private FileMessage(com.google.protobuf.GeneratedMessageV3.Builder<?> builder) {
      super(builder);
    }
    private FileMessage() {
      name_ = "";
      subFiles_ = java.util.Collections.emptyList();
      fileContent_ = com.google.protobuf.ByteString.EMPTY;
    }

    @java.lang.Override
    @SuppressWarnings({"unused"})
    protected java.lang.Object newInstance(
        UnusedPrivateParameter unused) {
      return new FileMessage();
    }

    @java.lang.Override
    public final com.google.protobuf.UnknownFieldSet
    getUnknownFields() {
      return this.unknownFields;
    }
    private FileMessage(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      this();
      if (extensionRegistry == null) {
        throw new java.lang.NullPointerException();
      }
      int mutable_bitField0_ = 0;
      com.google.protobuf.UnknownFieldSet.Builder unknownFields =
          com.google.protobuf.UnknownFieldSet.newBuilder();
      try {
        boolean done = false;
        while (!done) {
          int tag = input.readTag();
          switch (tag) {
            case 0:
              done = true;
              break;
            case 10: {
              java.lang.String s = input.readStringRequireUtf8();

              name_ = s;
              break;
            }
            case 18: {
              if (!((mutable_bitField0_ & 0x00000001) != 0)) {
                subFiles_ = new java.util.ArrayList<com.stupidbeauty.hxlauncher.FileMessageOuterClass.FileMessage>();
                mutable_bitField0_ |= 0x00000001;
              }
              subFiles_.add(
                  input.readMessage(com.stupidbeauty.hxlauncher.FileMessageOuterClass.FileMessage.parser(), extensionRegistry));
              break;
            }
            case 24: {

              isFile_ = input.readBool();
              break;
            }
            case 34: {

              fileContent_ = input.readBytes();
              break;
            }
            case 40: {

              fileStartIndex_ = input.readInt32();
              break;
            }
            case 48: {

              fileLength_ = input.readInt32();
              break;
            }
            case 56: {

              isCompressed_ = input.readBool();
              break;
            }
            default: {
              if (!parseUnknownField(
                  input, unknownFields, extensionRegistry, tag)) {
                done = true;
              }
              break;
            }
          }
        }
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        throw e.setUnfinishedMessage(this);
      } catch (java.io.IOException e) {
        throw new com.google.protobuf.InvalidProtocolBufferException(
            e).setUnfinishedMessage(this);
      } finally {
        if (((mutable_bitField0_ & 0x00000001) != 0)) {
          subFiles_ = java.util.Collections.unmodifiableList(subFiles_);
        }
        this.unknownFields = unknownFields.build();
        makeExtensionsImmutable();
      }
    }
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return com.stupidbeauty.hxlauncher.FileMessageOuterClass.internal_static_com_stupidbeauty_hxlauncher_FileMessage_descriptor;
    }

    @java.lang.Override
    protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return com.stupidbeauty.hxlauncher.FileMessageOuterClass.internal_static_com_stupidbeauty_hxlauncher_FileMessage_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              com.stupidbeauty.hxlauncher.FileMessageOuterClass.FileMessage.class, com.stupidbeauty.hxlauncher.FileMessageOuterClass.FileMessage.Builder.class);
    }

    public static final int NAME_FIELD_NUMBER = 1;
    private volatile java.lang.Object name_;
    /**
     * <pre>
     *文件或目录名字。
     * </pre>
     *
     * <code>string name = 1;</code>
     * @return The name.
     */
    public java.lang.String getName() {
      java.lang.Object ref = name_;
      if (ref instanceof java.lang.String) {
        return (java.lang.String) ref;
      } else {
        com.google.protobuf.ByteString bs = 
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        name_ = s;
        return s;
      }
    }
    /**
     * <pre>
     *文件或目录名字。
     * </pre>
     *
     * <code>string name = 1;</code>
     * @return The bytes for name.
     */
    public com.google.protobuf.ByteString
        getNameBytes() {
      java.lang.Object ref = name_;
      if (ref instanceof java.lang.String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        name_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }

    public static final int SUB_FILES_FIELD_NUMBER = 2;
    private java.util.List<com.stupidbeauty.hxlauncher.FileMessageOuterClass.FileMessage> subFiles_;
    /**
     * <pre>
     *子文件或目录列表。
     * </pre>
     *
     * <code>repeated .com.stupidbeauty.hxlauncher.FileMessage sub_files = 2;</code>
     */
    public java.util.List<com.stupidbeauty.hxlauncher.FileMessageOuterClass.FileMessage> getSubFilesList() {
      return subFiles_;
    }
    /**
     * <pre>
     *子文件或目录列表。
     * </pre>
     *
     * <code>repeated .com.stupidbeauty.hxlauncher.FileMessage sub_files = 2;</code>
     */
    public java.util.List<? extends com.stupidbeauty.hxlauncher.FileMessageOuterClass.FileMessageOrBuilder> 
        getSubFilesOrBuilderList() {
      return subFiles_;
    }
    /**
     * <pre>
     *子文件或目录列表。
     * </pre>
     *
     * <code>repeated .com.stupidbeauty.hxlauncher.FileMessage sub_files = 2;</code>
     */
    public int getSubFilesCount() {
      return subFiles_.size();
    }
    /**
     * <pre>
     *子文件或目录列表。
     * </pre>
     *
     * <code>repeated .com.stupidbeauty.hxlauncher.FileMessage sub_files = 2;</code>
     */
    public com.stupidbeauty.hxlauncher.FileMessageOuterClass.FileMessage getSubFiles(int index) {
      return subFiles_.get(index);
    }
    /**
     * <pre>
     *子文件或目录列表。
     * </pre>
     *
     * <code>repeated .com.stupidbeauty.hxlauncher.FileMessage sub_files = 2;</code>
     */
    public com.stupidbeauty.hxlauncher.FileMessageOuterClass.FileMessageOrBuilder getSubFilesOrBuilder(
        int index) {
      return subFiles_.get(index);
    }

    public static final int IS_FILE_FIELD_NUMBER = 3;
    private boolean isFile_;
    /**
     * <pre>
     *是否是文件。
     * </pre>
     *
     * <code>bool is_file = 3;</code>
     * @return The isFile.
     */
    public boolean getIsFile() {
      return isFile_;
    }

    public static final int FILE_CONTENT_FIELD_NUMBER = 4;
    private com.google.protobuf.ByteString fileContent_;
    /**
     * <pre>
     *文件内容。
     * </pre>
     *
     * <code>bytes file_content = 4;</code>
     * @return The fileContent.
     */
    public com.google.protobuf.ByteString getFileContent() {
      return fileContent_;
    }

    public static final int FILE_START_INDEX_FIELD_NUMBER = 5;
    private int fileStartIndex_;
    /**
     * <pre>
     *这个文件的内容在victoriafreshdata大文件中的起始位置。
     * </pre>
     *
     * <code>int32 file_start_index = 5;</code>
     * @return The fileStartIndex.
     */
    public int getFileStartIndex() {
      return fileStartIndex_;
    }

    public static final int FILE_LENGTH_FIELD_NUMBER = 6;
    private int fileLength_;
    /**
     * <pre>
     *这个文件的内容的长度。
     * </pre>
     *
     * <code>int32 file_length = 6;</code>
     * @return The fileLength.
     */
    public int getFileLength() {
      return fileLength_;
    }

    public static final int ISCOMPRESSED_FIELD_NUMBER = 7;
    private boolean isCompressed_;
    /**
     * <pre>
     *!&lt;文件内容是否被压缩了
     * </pre>
     *
     * <code>bool isCompressed = 7;</code>
     * @return The isCompressed.
     */
    public boolean getIsCompressed() {
      return isCompressed_;
    }

    private byte memoizedIsInitialized = -1;
    @java.lang.Override
    public final boolean isInitialized() {
      byte isInitialized = memoizedIsInitialized;
      if (isInitialized == 1) return true;
      if (isInitialized == 0) return false;

      memoizedIsInitialized = 1;
      return true;
    }

    @java.lang.Override
    public void writeTo(com.google.protobuf.CodedOutputStream output)
                        throws java.io.IOException {
      if (!getNameBytes().isEmpty()) {
        com.google.protobuf.GeneratedMessageV3.writeString(output, 1, name_);
      }
      for (int i = 0; i < subFiles_.size(); i++) {
        output.writeMessage(2, subFiles_.get(i));
      }
      if (isFile_ != false) {
        output.writeBool(3, isFile_);
      }
      if (!fileContent_.isEmpty()) {
        output.writeBytes(4, fileContent_);
      }
      if (fileStartIndex_ != 0) {
        output.writeInt32(5, fileStartIndex_);
      }
      if (fileLength_ != 0) {
        output.writeInt32(6, fileLength_);
      }
      if (isCompressed_ != false) {
        output.writeBool(7, isCompressed_);
      }
      unknownFields.writeTo(output);
    }

    @java.lang.Override
    public int getSerializedSize() {
      int size = memoizedSize;
      if (size != -1) return size;

      size = 0;
      if (!getNameBytes().isEmpty()) {
        size += com.google.protobuf.GeneratedMessageV3.computeStringSize(1, name_);
      }
      for (int i = 0; i < subFiles_.size(); i++) {
        size += com.google.protobuf.CodedOutputStream
          .computeMessageSize(2, subFiles_.get(i));
      }
      if (isFile_ != false) {
        size += com.google.protobuf.CodedOutputStream
          .computeBoolSize(3, isFile_);
      }
      if (!fileContent_.isEmpty()) {
        size += com.google.protobuf.CodedOutputStream
          .computeBytesSize(4, fileContent_);
      }
      if (fileStartIndex_ != 0) {
        size += com.google.protobuf.CodedOutputStream
          .computeInt32Size(5, fileStartIndex_);
      }
      if (fileLength_ != 0) {
        size += com.google.protobuf.CodedOutputStream
          .computeInt32Size(6, fileLength_);
      }
      if (isCompressed_ != false) {
        size += com.google.protobuf.CodedOutputStream
          .computeBoolSize(7, isCompressed_);
      }
      size += unknownFields.getSerializedSize();
      memoizedSize = size;
      return size;
    }

    @java.lang.Override
    public boolean equals(final java.lang.Object obj) {
      if (obj == this) {
       return true;
      }
      if (!(obj instanceof com.stupidbeauty.hxlauncher.FileMessageOuterClass.FileMessage)) {
        return super.equals(obj);
      }
      com.stupidbeauty.hxlauncher.FileMessageOuterClass.FileMessage other = (com.stupidbeauty.hxlauncher.FileMessageOuterClass.FileMessage) obj;

      if (!getName()
          .equals(other.getName())) return false;
      if (!getSubFilesList()
          .equals(other.getSubFilesList())) return false;
      if (getIsFile()
          != other.getIsFile()) return false;
      if (!getFileContent()
          .equals(other.getFileContent())) return false;
      if (getFileStartIndex()
          != other.getFileStartIndex()) return false;
      if (getFileLength()
          != other.getFileLength()) return false;
      if (getIsCompressed()
          != other.getIsCompressed()) return false;
      if (!unknownFields.equals(other.unknownFields)) return false;
      return true;
    }

    @java.lang.Override
    public int hashCode() {
      if (memoizedHashCode != 0) {
        return memoizedHashCode;
      }
      int hash = 41;
      hash = (19 * hash) + getDescriptor().hashCode();
      hash = (37 * hash) + NAME_FIELD_NUMBER;
      hash = (53 * hash) + getName().hashCode();
      if (getSubFilesCount() > 0) {
        hash = (37 * hash) + SUB_FILES_FIELD_NUMBER;
        hash = (53 * hash) + getSubFilesList().hashCode();
      }
      hash = (37 * hash) + IS_FILE_FIELD_NUMBER;
      hash = (53 * hash) + com.google.protobuf.Internal.hashBoolean(
          getIsFile());
      hash = (37 * hash) + FILE_CONTENT_FIELD_NUMBER;
      hash = (53 * hash) + getFileContent().hashCode();
      hash = (37 * hash) + FILE_START_INDEX_FIELD_NUMBER;
      hash = (53 * hash) + getFileStartIndex();
      hash = (37 * hash) + FILE_LENGTH_FIELD_NUMBER;
      hash = (53 * hash) + getFileLength();
      hash = (37 * hash) + ISCOMPRESSED_FIELD_NUMBER;
      hash = (53 * hash) + com.google.protobuf.Internal.hashBoolean(
          getIsCompressed());
      hash = (29 * hash) + unknownFields.hashCode();
      memoizedHashCode = hash;
      return hash;
    }

    public static com.stupidbeauty.hxlauncher.FileMessageOuterClass.FileMessage parseFrom(
        java.nio.ByteBuffer data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static com.stupidbeauty.hxlauncher.FileMessageOuterClass.FileMessage parseFrom(
        java.nio.ByteBuffer data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static com.stupidbeauty.hxlauncher.FileMessageOuterClass.FileMessage parseFrom(
        com.google.protobuf.ByteString data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static com.stupidbeauty.hxlauncher.FileMessageOuterClass.FileMessage parseFrom(
        com.google.protobuf.ByteString data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static com.stupidbeauty.hxlauncher.FileMessageOuterClass.FileMessage parseFrom(byte[] data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static com.stupidbeauty.hxlauncher.FileMessageOuterClass.FileMessage parseFrom(
        byte[] data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static com.stupidbeauty.hxlauncher.FileMessageOuterClass.FileMessage parseFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input);
    }
    public static com.stupidbeauty.hxlauncher.FileMessageOuterClass.FileMessage parseFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input, extensionRegistry);
    }
    public static com.stupidbeauty.hxlauncher.FileMessageOuterClass.FileMessage parseDelimitedFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseDelimitedWithIOException(PARSER, input);
    }
    public static com.stupidbeauty.hxlauncher.FileMessageOuterClass.FileMessage parseDelimitedFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseDelimitedWithIOException(PARSER, input, extensionRegistry);
    }
    public static com.stupidbeauty.hxlauncher.FileMessageOuterClass.FileMessage parseFrom(
        com.google.protobuf.CodedInputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input);
    }
    public static com.stupidbeauty.hxlauncher.FileMessageOuterClass.FileMessage parseFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input, extensionRegistry);
    }

    @java.lang.Override
    public Builder newBuilderForType() { return newBuilder(); }
    public static Builder newBuilder() {
      return DEFAULT_INSTANCE.toBuilder();
    }
    public static Builder newBuilder(com.stupidbeauty.hxlauncher.FileMessageOuterClass.FileMessage prototype) {
      return DEFAULT_INSTANCE.toBuilder().mergeFrom(prototype);
    }
    @java.lang.Override
    public Builder toBuilder() {
      return this == DEFAULT_INSTANCE
          ? new Builder() : new Builder().mergeFrom(this);
    }

    @java.lang.Override
    protected Builder newBuilderForType(
        com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
      Builder builder = new Builder(parent);
      return builder;
    }
    /**
     * Protobuf type {@code com.stupidbeauty.hxlauncher.FileMessage}
     */
    public static final class Builder extends
        com.google.protobuf.GeneratedMessageV3.Builder<Builder> implements
        // @@protoc_insertion_point(builder_implements:com.stupidbeauty.hxlauncher.FileMessage)
        com.stupidbeauty.hxlauncher.FileMessageOuterClass.FileMessageOrBuilder {
      public static final com.google.protobuf.Descriptors.Descriptor
          getDescriptor() {
        return com.stupidbeauty.hxlauncher.FileMessageOuterClass.internal_static_com_stupidbeauty_hxlauncher_FileMessage_descriptor;
      }

      @java.lang.Override
      protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
          internalGetFieldAccessorTable() {
        return com.stupidbeauty.hxlauncher.FileMessageOuterClass.internal_static_com_stupidbeauty_hxlauncher_FileMessage_fieldAccessorTable
            .ensureFieldAccessorsInitialized(
                com.stupidbeauty.hxlauncher.FileMessageOuterClass.FileMessage.class, com.stupidbeauty.hxlauncher.FileMessageOuterClass.FileMessage.Builder.class);
      }

      // Construct using com.stupidbeauty.hxlauncher.FileMessageOuterClass.FileMessage.newBuilder()
      private Builder() {
        maybeForceBuilderInitialization();
      }

      private Builder(
          com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
        super(parent);
        maybeForceBuilderInitialization();
      }
      private void maybeForceBuilderInitialization() {
        if (com.google.protobuf.GeneratedMessageV3
                .alwaysUseFieldBuilders) {
          getSubFilesFieldBuilder();
        }
      }
      @java.lang.Override
      public Builder clear() {
        super.clear();
        name_ = "";

        if (subFilesBuilder_ == null) {
          subFiles_ = java.util.Collections.emptyList();
          bitField0_ = (bitField0_ & ~0x00000001);
        } else {
          subFilesBuilder_.clear();
        }
        isFile_ = false;

        fileContent_ = com.google.protobuf.ByteString.EMPTY;

        fileStartIndex_ = 0;

        fileLength_ = 0;

        isCompressed_ = false;

        return this;
      }

      @java.lang.Override
      public com.google.protobuf.Descriptors.Descriptor
          getDescriptorForType() {
        return com.stupidbeauty.hxlauncher.FileMessageOuterClass.internal_static_com_stupidbeauty_hxlauncher_FileMessage_descriptor;
      }

      @java.lang.Override
      public com.stupidbeauty.hxlauncher.FileMessageOuterClass.FileMessage getDefaultInstanceForType() {
        return com.stupidbeauty.hxlauncher.FileMessageOuterClass.FileMessage.getDefaultInstance();
      }

      @java.lang.Override
      public com.stupidbeauty.hxlauncher.FileMessageOuterClass.FileMessage build() {
        com.stupidbeauty.hxlauncher.FileMessageOuterClass.FileMessage result = buildPartial();
        if (!result.isInitialized()) {
          throw newUninitializedMessageException(result);
        }
        return result;
      }

      @java.lang.Override
      public com.stupidbeauty.hxlauncher.FileMessageOuterClass.FileMessage buildPartial() {
        com.stupidbeauty.hxlauncher.FileMessageOuterClass.FileMessage result = new com.stupidbeauty.hxlauncher.FileMessageOuterClass.FileMessage(this);
        int from_bitField0_ = bitField0_;
        result.name_ = name_;
        if (subFilesBuilder_ == null) {
          if (((bitField0_ & 0x00000001) != 0)) {
            subFiles_ = java.util.Collections.unmodifiableList(subFiles_);
            bitField0_ = (bitField0_ & ~0x00000001);
          }
          result.subFiles_ = subFiles_;
        } else {
          result.subFiles_ = subFilesBuilder_.build();
        }
        result.isFile_ = isFile_;
        result.fileContent_ = fileContent_;
        result.fileStartIndex_ = fileStartIndex_;
        result.fileLength_ = fileLength_;
        result.isCompressed_ = isCompressed_;
        onBuilt();
        return result;
      }

      @java.lang.Override
      public Builder clone() {
        return super.clone();
      }
      @java.lang.Override
      public Builder setField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          java.lang.Object value) {
        return super.setField(field, value);
      }
      @java.lang.Override
      public Builder clearField(
          com.google.protobuf.Descriptors.FieldDescriptor field) {
        return super.clearField(field);
      }
      @java.lang.Override
      public Builder clearOneof(
          com.google.protobuf.Descriptors.OneofDescriptor oneof) {
        return super.clearOneof(oneof);
      }
      @java.lang.Override
      public Builder setRepeatedField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          int index, java.lang.Object value) {
        return super.setRepeatedField(field, index, value);
      }
      @java.lang.Override
      public Builder addRepeatedField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          java.lang.Object value) {
        return super.addRepeatedField(field, value);
      }
      @java.lang.Override
      public Builder mergeFrom(com.google.protobuf.Message other) {
        if (other instanceof com.stupidbeauty.hxlauncher.FileMessageOuterClass.FileMessage) {
          return mergeFrom((com.stupidbeauty.hxlauncher.FileMessageOuterClass.FileMessage)other);
        } else {
          super.mergeFrom(other);
          return this;
        }
      }

      public Builder mergeFrom(com.stupidbeauty.hxlauncher.FileMessageOuterClass.FileMessage other) {
        if (other == com.stupidbeauty.hxlauncher.FileMessageOuterClass.FileMessage.getDefaultInstance()) return this;
        if (!other.getName().isEmpty()) {
          name_ = other.name_;
          onChanged();
        }
        if (subFilesBuilder_ == null) {
          if (!other.subFiles_.isEmpty()) {
            if (subFiles_.isEmpty()) {
              subFiles_ = other.subFiles_;
              bitField0_ = (bitField0_ & ~0x00000001);
            } else {
              ensureSubFilesIsMutable();
              subFiles_.addAll(other.subFiles_);
            }
            onChanged();
          }
        } else {
          if (!other.subFiles_.isEmpty()) {
            if (subFilesBuilder_.isEmpty()) {
              subFilesBuilder_.dispose();
              subFilesBuilder_ = null;
              subFiles_ = other.subFiles_;
              bitField0_ = (bitField0_ & ~0x00000001);
              subFilesBuilder_ = 
                com.google.protobuf.GeneratedMessageV3.alwaysUseFieldBuilders ?
                   getSubFilesFieldBuilder() : null;
            } else {
              subFilesBuilder_.addAllMessages(other.subFiles_);
            }
          }
        }
        if (other.getIsFile() != false) {
          setIsFile(other.getIsFile());
        }
        if (other.getFileContent() != com.google.protobuf.ByteString.EMPTY) {
          setFileContent(other.getFileContent());
        }
        if (other.getFileStartIndex() != 0) {
          setFileStartIndex(other.getFileStartIndex());
        }
        if (other.getFileLength() != 0) {
          setFileLength(other.getFileLength());
        }
        if (other.getIsCompressed() != false) {
          setIsCompressed(other.getIsCompressed());
        }
        this.mergeUnknownFields(other.unknownFields);
        onChanged();
        return this;
      }

      @java.lang.Override
      public final boolean isInitialized() {
        return true;
      }

      @java.lang.Override
      public Builder mergeFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws java.io.IOException {
        com.stupidbeauty.hxlauncher.FileMessageOuterClass.FileMessage parsedMessage = null;
        try {
          parsedMessage = PARSER.parsePartialFrom(input, extensionRegistry);
        } catch (com.google.protobuf.InvalidProtocolBufferException e) {
          parsedMessage = (com.stupidbeauty.hxlauncher.FileMessageOuterClass.FileMessage) e.getUnfinishedMessage();
          throw e.unwrapIOException();
        } finally {
          if (parsedMessage != null) {
            mergeFrom(parsedMessage);
          }
        }
        return this;
      }
      private int bitField0_;

      private java.lang.Object name_ = "";
      /**
       * <pre>
       *文件或目录名字。
       * </pre>
       *
       * <code>string name = 1;</code>
       * @return The name.
       */
      public java.lang.String getName() {
        java.lang.Object ref = name_;
        if (!(ref instanceof java.lang.String)) {
          com.google.protobuf.ByteString bs =
              (com.google.protobuf.ByteString) ref;
          java.lang.String s = bs.toStringUtf8();
          name_ = s;
          return s;
        } else {
          return (java.lang.String) ref;
        }
      }
      /**
       * <pre>
       *文件或目录名字。
       * </pre>
       *
       * <code>string name = 1;</code>
       * @return The bytes for name.
       */
      public com.google.protobuf.ByteString
          getNameBytes() {
        java.lang.Object ref = name_;
        if (ref instanceof String) {
          com.google.protobuf.ByteString b = 
              com.google.protobuf.ByteString.copyFromUtf8(
                  (java.lang.String) ref);
          name_ = b;
          return b;
        } else {
          return (com.google.protobuf.ByteString) ref;
        }
      }
      /**
       * <pre>
       *文件或目录名字。
       * </pre>
       *
       * <code>string name = 1;</code>
       * @param value The name to set.
       * @return This builder for chaining.
       */
      public Builder setName(
          java.lang.String value) {
        if (value == null) {
    throw new NullPointerException();
  }
  
        name_ = value;
        onChanged();
        return this;
      }
      /**
       * <pre>
       *文件或目录名字。
       * </pre>
       *
       * <code>string name = 1;</code>
       * @return This builder for chaining.
       */
      public Builder clearName() {
        
        name_ = getDefaultInstance().getName();
        onChanged();
        return this;
      }
      /**
       * <pre>
       *文件或目录名字。
       * </pre>
       *
       * <code>string name = 1;</code>
       * @param value The bytes for name to set.
       * @return This builder for chaining.
       */
      public Builder setNameBytes(
          com.google.protobuf.ByteString value) {
        if (value == null) {
    throw new NullPointerException();
  }
  checkByteStringIsUtf8(value);
        
        name_ = value;
        onChanged();
        return this;
      }

      private java.util.List<com.stupidbeauty.hxlauncher.FileMessageOuterClass.FileMessage> subFiles_ =
        java.util.Collections.emptyList();
      private void ensureSubFilesIsMutable() {
        if (!((bitField0_ & 0x00000001) != 0)) {
          subFiles_ = new java.util.ArrayList<com.stupidbeauty.hxlauncher.FileMessageOuterClass.FileMessage>(subFiles_);
          bitField0_ |= 0x00000001;
         }
      }

      private com.google.protobuf.RepeatedFieldBuilderV3<
          com.stupidbeauty.hxlauncher.FileMessageOuterClass.FileMessage, com.stupidbeauty.hxlauncher.FileMessageOuterClass.FileMessage.Builder, com.stupidbeauty.hxlauncher.FileMessageOuterClass.FileMessageOrBuilder> subFilesBuilder_;

      /**
       * <pre>
       *子文件或目录列表。
       * </pre>
       *
       * <code>repeated .com.stupidbeauty.hxlauncher.FileMessage sub_files = 2;</code>
       */
      public java.util.List<com.stupidbeauty.hxlauncher.FileMessageOuterClass.FileMessage> getSubFilesList() {
        if (subFilesBuilder_ == null) {
          return java.util.Collections.unmodifiableList(subFiles_);
        } else {
          return subFilesBuilder_.getMessageList();
        }
      }
      /**
       * <pre>
       *子文件或目录列表。
       * </pre>
       *
       * <code>repeated .com.stupidbeauty.hxlauncher.FileMessage sub_files = 2;</code>
       */
      public int getSubFilesCount() {
        if (subFilesBuilder_ == null) {
          return subFiles_.size();
        } else {
          return subFilesBuilder_.getCount();
        }
      }
      /**
       * <pre>
       *子文件或目录列表。
       * </pre>
       *
       * <code>repeated .com.stupidbeauty.hxlauncher.FileMessage sub_files = 2;</code>
       */
      public com.stupidbeauty.hxlauncher.FileMessageOuterClass.FileMessage getSubFiles(int index) {
        if (subFilesBuilder_ == null) {
          return subFiles_.get(index);
        } else {
          return subFilesBuilder_.getMessage(index);
        }
      }
      /**
       * <pre>
       *子文件或目录列表。
       * </pre>
       *
       * <code>repeated .com.stupidbeauty.hxlauncher.FileMessage sub_files = 2;</code>
       */
      public Builder setSubFiles(
          int index, com.stupidbeauty.hxlauncher.FileMessageOuterClass.FileMessage value) {
        if (subFilesBuilder_ == null) {
          if (value == null) {
            throw new NullPointerException();
          }
          ensureSubFilesIsMutable();
          subFiles_.set(index, value);
          onChanged();
        } else {
          subFilesBuilder_.setMessage(index, value);
        }
        return this;
      }
      /**
       * <pre>
       *子文件或目录列表。
       * </pre>
       *
       * <code>repeated .com.stupidbeauty.hxlauncher.FileMessage sub_files = 2;</code>
       */
      public Builder setSubFiles(
          int index, com.stupidbeauty.hxlauncher.FileMessageOuterClass.FileMessage.Builder builderForValue) {
        if (subFilesBuilder_ == null) {
          ensureSubFilesIsMutable();
          subFiles_.set(index, builderForValue.build());
          onChanged();
        } else {
          subFilesBuilder_.setMessage(index, builderForValue.build());
        }
        return this;
      }
      /**
       * <pre>
       *子文件或目录列表。
       * </pre>
       *
       * <code>repeated .com.stupidbeauty.hxlauncher.FileMessage sub_files = 2;</code>
       */
      public Builder addSubFiles(com.stupidbeauty.hxlauncher.FileMessageOuterClass.FileMessage value) {
        if (subFilesBuilder_ == null) {
          if (value == null) {
            throw new NullPointerException();
          }
          ensureSubFilesIsMutable();
          subFiles_.add(value);
          onChanged();
        } else {
          subFilesBuilder_.addMessage(value);
        }
        return this;
      }
      /**
       * <pre>
       *子文件或目录列表。
       * </pre>
       *
       * <code>repeated .com.stupidbeauty.hxlauncher.FileMessage sub_files = 2;</code>
       */
      public Builder addSubFiles(
          int index, com.stupidbeauty.hxlauncher.FileMessageOuterClass.FileMessage value) {
        if (subFilesBuilder_ == null) {
          if (value == null) {
            throw new NullPointerException();
          }
          ensureSubFilesIsMutable();
          subFiles_.add(index, value);
          onChanged();
        } else {
          subFilesBuilder_.addMessage(index, value);
        }
        return this;
      }
      /**
       * <pre>
       *子文件或目录列表。
       * </pre>
       *
       * <code>repeated .com.stupidbeauty.hxlauncher.FileMessage sub_files = 2;</code>
       */
      public Builder addSubFiles(
          com.stupidbeauty.hxlauncher.FileMessageOuterClass.FileMessage.Builder builderForValue) {
        if (subFilesBuilder_ == null) {
          ensureSubFilesIsMutable();
          subFiles_.add(builderForValue.build());
          onChanged();
        } else {
          subFilesBuilder_.addMessage(builderForValue.build());
        }
        return this;
      }
      /**
       * <pre>
       *子文件或目录列表。
       * </pre>
       *
       * <code>repeated .com.stupidbeauty.hxlauncher.FileMessage sub_files = 2;</code>
       */
      public Builder addSubFiles(
          int index, com.stupidbeauty.hxlauncher.FileMessageOuterClass.FileMessage.Builder builderForValue) {
        if (subFilesBuilder_ == null) {
          ensureSubFilesIsMutable();
          subFiles_.add(index, builderForValue.build());
          onChanged();
        } else {
          subFilesBuilder_.addMessage(index, builderForValue.build());
        }
        return this;
      }
      /**
       * <pre>
       *子文件或目录列表。
       * </pre>
       *
       * <code>repeated .com.stupidbeauty.hxlauncher.FileMessage sub_files = 2;</code>
       */
      public Builder addAllSubFiles(
          java.lang.Iterable<? extends com.stupidbeauty.hxlauncher.FileMessageOuterClass.FileMessage> values) {
        if (subFilesBuilder_ == null) {
          ensureSubFilesIsMutable();
          com.google.protobuf.AbstractMessageLite.Builder.addAll(
              values, subFiles_);
          onChanged();
        } else {
          subFilesBuilder_.addAllMessages(values);
        }
        return this;
      }
      /**
       * <pre>
       *子文件或目录列表。
       * </pre>
       *
       * <code>repeated .com.stupidbeauty.hxlauncher.FileMessage sub_files = 2;</code>
       */
      public Builder clearSubFiles() {
        if (subFilesBuilder_ == null) {
          subFiles_ = java.util.Collections.emptyList();
          bitField0_ = (bitField0_ & ~0x00000001);
          onChanged();
        } else {
          subFilesBuilder_.clear();
        }
        return this;
      }
      /**
       * <pre>
       *子文件或目录列表。
       * </pre>
       *
       * <code>repeated .com.stupidbeauty.hxlauncher.FileMessage sub_files = 2;</code>
       */
      public Builder removeSubFiles(int index) {
        if (subFilesBuilder_ == null) {
          ensureSubFilesIsMutable();
          subFiles_.remove(index);
          onChanged();
        } else {
          subFilesBuilder_.remove(index);
        }
        return this;
      }
      /**
       * <pre>
       *子文件或目录列表。
       * </pre>
       *
       * <code>repeated .com.stupidbeauty.hxlauncher.FileMessage sub_files = 2;</code>
       */
      public com.stupidbeauty.hxlauncher.FileMessageOuterClass.FileMessage.Builder getSubFilesBuilder(
          int index) {
        return getSubFilesFieldBuilder().getBuilder(index);
      }
      /**
       * <pre>
       *子文件或目录列表。
       * </pre>
       *
       * <code>repeated .com.stupidbeauty.hxlauncher.FileMessage sub_files = 2;</code>
       */
      public com.stupidbeauty.hxlauncher.FileMessageOuterClass.FileMessageOrBuilder getSubFilesOrBuilder(
          int index) {
        if (subFilesBuilder_ == null) {
          return subFiles_.get(index);  } else {
          return subFilesBuilder_.getMessageOrBuilder(index);
        }
      }
      /**
       * <pre>
       *子文件或目录列表。
       * </pre>
       *
       * <code>repeated .com.stupidbeauty.hxlauncher.FileMessage sub_files = 2;</code>
       */
      public java.util.List<? extends com.stupidbeauty.hxlauncher.FileMessageOuterClass.FileMessageOrBuilder> 
           getSubFilesOrBuilderList() {
        if (subFilesBuilder_ != null) {
          return subFilesBuilder_.getMessageOrBuilderList();
        } else {
          return java.util.Collections.unmodifiableList(subFiles_);
        }
      }
      /**
       * <pre>
       *子文件或目录列表。
       * </pre>
       *
       * <code>repeated .com.stupidbeauty.hxlauncher.FileMessage sub_files = 2;</code>
       */
      public com.stupidbeauty.hxlauncher.FileMessageOuterClass.FileMessage.Builder addSubFilesBuilder() {
        return getSubFilesFieldBuilder().addBuilder(
            com.stupidbeauty.hxlauncher.FileMessageOuterClass.FileMessage.getDefaultInstance());
      }
      /**
       * <pre>
       *子文件或目录列表。
       * </pre>
       *
       * <code>repeated .com.stupidbeauty.hxlauncher.FileMessage sub_files = 2;</code>
       */
      public com.stupidbeauty.hxlauncher.FileMessageOuterClass.FileMessage.Builder addSubFilesBuilder(
          int index) {
        return getSubFilesFieldBuilder().addBuilder(
            index, com.stupidbeauty.hxlauncher.FileMessageOuterClass.FileMessage.getDefaultInstance());
      }
      /**
       * <pre>
       *子文件或目录列表。
       * </pre>
       *
       * <code>repeated .com.stupidbeauty.hxlauncher.FileMessage sub_files = 2;</code>
       */
      public java.util.List<com.stupidbeauty.hxlauncher.FileMessageOuterClass.FileMessage.Builder> 
           getSubFilesBuilderList() {
        return getSubFilesFieldBuilder().getBuilderList();
      }
      private com.google.protobuf.RepeatedFieldBuilderV3<
          com.stupidbeauty.hxlauncher.FileMessageOuterClass.FileMessage, com.stupidbeauty.hxlauncher.FileMessageOuterClass.FileMessage.Builder, com.stupidbeauty.hxlauncher.FileMessageOuterClass.FileMessageOrBuilder> 
          getSubFilesFieldBuilder() {
        if (subFilesBuilder_ == null) {
          subFilesBuilder_ = new com.google.protobuf.RepeatedFieldBuilderV3<
              com.stupidbeauty.hxlauncher.FileMessageOuterClass.FileMessage, com.stupidbeauty.hxlauncher.FileMessageOuterClass.FileMessage.Builder, com.stupidbeauty.hxlauncher.FileMessageOuterClass.FileMessageOrBuilder>(
                  subFiles_,
                  ((bitField0_ & 0x00000001) != 0),
                  getParentForChildren(),
                  isClean());
          subFiles_ = null;
        }
        return subFilesBuilder_;
      }

      private boolean isFile_ ;
      /**
       * <pre>
       *是否是文件。
       * </pre>
       *
       * <code>bool is_file = 3;</code>
       * @return The isFile.
       */
      public boolean getIsFile() {
        return isFile_;
      }
      /**
       * <pre>
       *是否是文件。
       * </pre>
       *
       * <code>bool is_file = 3;</code>
       * @param value The isFile to set.
       * @return This builder for chaining.
       */
      public Builder setIsFile(boolean value) {
        
        isFile_ = value;
        onChanged();
        return this;
      }
      /**
       * <pre>
       *是否是文件。
       * </pre>
       *
       * <code>bool is_file = 3;</code>
       * @return This builder for chaining.
       */
      public Builder clearIsFile() {
        
        isFile_ = false;
        onChanged();
        return this;
      }

      private com.google.protobuf.ByteString fileContent_ = com.google.protobuf.ByteString.EMPTY;
      /**
       * <pre>
       *文件内容。
       * </pre>
       *
       * <code>bytes file_content = 4;</code>
       * @return The fileContent.
       */
      public com.google.protobuf.ByteString getFileContent() {
        return fileContent_;
      }
      /**
       * <pre>
       *文件内容。
       * </pre>
       *
       * <code>bytes file_content = 4;</code>
       * @param value The fileContent to set.
       * @return This builder for chaining.
       */
      public Builder setFileContent(com.google.protobuf.ByteString value) {
        if (value == null) {
    throw new NullPointerException();
  }
  
        fileContent_ = value;
        onChanged();
        return this;
      }
      /**
       * <pre>
       *文件内容。
       * </pre>
       *
       * <code>bytes file_content = 4;</code>
       * @return This builder for chaining.
       */
      public Builder clearFileContent() {
        
        fileContent_ = getDefaultInstance().getFileContent();
        onChanged();
        return this;
      }

      private int fileStartIndex_ ;
      /**
       * <pre>
       *这个文件的内容在victoriafreshdata大文件中的起始位置。
       * </pre>
       *
       * <code>int32 file_start_index = 5;</code>
       * @return The fileStartIndex.
       */
      public int getFileStartIndex() {
        return fileStartIndex_;
      }
      /**
       * <pre>
       *这个文件的内容在victoriafreshdata大文件中的起始位置。
       * </pre>
       *
       * <code>int32 file_start_index = 5;</code>
       * @param value The fileStartIndex to set.
       * @return This builder for chaining.
       */
      public Builder setFileStartIndex(int value) {
        
        fileStartIndex_ = value;
        onChanged();
        return this;
      }
      /**
       * <pre>
       *这个文件的内容在victoriafreshdata大文件中的起始位置。
       * </pre>
       *
       * <code>int32 file_start_index = 5;</code>
       * @return This builder for chaining.
       */
      public Builder clearFileStartIndex() {
        
        fileStartIndex_ = 0;
        onChanged();
        return this;
      }

      private int fileLength_ ;
      /**
       * <pre>
       *这个文件的内容的长度。
       * </pre>
       *
       * <code>int32 file_length = 6;</code>
       * @return The fileLength.
       */
      public int getFileLength() {
        return fileLength_;
      }
      /**
       * <pre>
       *这个文件的内容的长度。
       * </pre>
       *
       * <code>int32 file_length = 6;</code>
       * @param value The fileLength to set.
       * @return This builder for chaining.
       */
      public Builder setFileLength(int value) {
        
        fileLength_ = value;
        onChanged();
        return this;
      }
      /**
       * <pre>
       *这个文件的内容的长度。
       * </pre>
       *
       * <code>int32 file_length = 6;</code>
       * @return This builder for chaining.
       */
      public Builder clearFileLength() {
        
        fileLength_ = 0;
        onChanged();
        return this;
      }

      private boolean isCompressed_ ;
      /**
       * <pre>
       *!&lt;文件内容是否被压缩了
       * </pre>
       *
       * <code>bool isCompressed = 7;</code>
       * @return The isCompressed.
       */
      public boolean getIsCompressed() {
        return isCompressed_;
      }
      /**
       * <pre>
       *!&lt;文件内容是否被压缩了
       * </pre>
       *
       * <code>bool isCompressed = 7;</code>
       * @param value The isCompressed to set.
       * @return This builder for chaining.
       */
      public Builder setIsCompressed(boolean value) {
        
        isCompressed_ = value;
        onChanged();
        return this;
      }
      /**
       * <pre>
       *!&lt;文件内容是否被压缩了
       * </pre>
       *
       * <code>bool isCompressed = 7;</code>
       * @return This builder for chaining.
       */
      public Builder clearIsCompressed() {
        
        isCompressed_ = false;
        onChanged();
        return this;
      }
      @java.lang.Override
      public final Builder setUnknownFields(
          final com.google.protobuf.UnknownFieldSet unknownFields) {
        return super.setUnknownFields(unknownFields);
      }

      @java.lang.Override
      public final Builder mergeUnknownFields(
          final com.google.protobuf.UnknownFieldSet unknownFields) {
        return super.mergeUnknownFields(unknownFields);
      }


      // @@protoc_insertion_point(builder_scope:com.stupidbeauty.hxlauncher.FileMessage)
    }

    // @@protoc_insertion_point(class_scope:com.stupidbeauty.hxlauncher.FileMessage)
    private static final com.stupidbeauty.hxlauncher.FileMessageOuterClass.FileMessage DEFAULT_INSTANCE;
    static {
      DEFAULT_INSTANCE = new com.stupidbeauty.hxlauncher.FileMessageOuterClass.FileMessage();
    }

    public static com.stupidbeauty.hxlauncher.FileMessageOuterClass.FileMessage getDefaultInstance() {
      return DEFAULT_INSTANCE;
    }

    private static final com.google.protobuf.Parser<FileMessage>
        PARSER = new com.google.protobuf.AbstractParser<FileMessage>() {
      @java.lang.Override
      public FileMessage parsePartialFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws com.google.protobuf.InvalidProtocolBufferException {
        return new FileMessage(input, extensionRegistry);
      }
    };

    public static com.google.protobuf.Parser<FileMessage> parser() {
      return PARSER;
    }

    @java.lang.Override
    public com.google.protobuf.Parser<FileMessage> getParserForType() {
      return PARSER;
    }

    @java.lang.Override
    public com.stupidbeauty.hxlauncher.FileMessageOuterClass.FileMessage getDefaultInstanceForType() {
      return DEFAULT_INSTANCE;
    }

  }

  private static final com.google.protobuf.Descriptors.Descriptor
    internal_static_com_stupidbeauty_hxlauncher_FileMessage_descriptor;
  private static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_com_stupidbeauty_hxlauncher_FileMessage_fieldAccessorTable;

  public static com.google.protobuf.Descriptors.FileDescriptor
      getDescriptor() {
    return descriptor;
  }
  private static  com.google.protobuf.Descriptors.FileDescriptor
      descriptor;
  static {
    java.lang.String[] descriptorData = {
      "\n\021FileMessage.proto\022\033com.stupidbeauty.hx" +
      "launcher\"\304\001\n\013FileMessage\022\014\n\004name\030\001 \001(\t\022;" +
      "\n\tsub_files\030\002 \003(\0132(.com.stupidbeauty.hxl" +
      "auncher.FileMessage\022\017\n\007is_file\030\003 \001(\010\022\024\n\014" +
      "file_content\030\004 \001(\014\022\030\n\020file_start_index\030\005" +
      " \001(\005\022\023\n\013file_length\030\006 \001(\005\022\024\n\014isCompresse" +
      "d\030\007 \001(\010b\006proto3"
    };
    descriptor = com.google.protobuf.Descriptors.FileDescriptor
      .internalBuildGeneratedFileFrom(descriptorData,
        new com.google.protobuf.Descriptors.FileDescriptor[] {
        });
    internal_static_com_stupidbeauty_hxlauncher_FileMessage_descriptor =
      getDescriptor().getMessageTypes().get(0);
    internal_static_com_stupidbeauty_hxlauncher_FileMessage_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_com_stupidbeauty_hxlauncher_FileMessage_descriptor,
        new java.lang.String[] { "Name", "SubFiles", "IsFile", "FileContent", "FileStartIndex", "FileLength", "IsCompressed", });
  }

  // @@protoc_insertion_point(outer_class_scope)
}
