// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: InstallerMessage.proto

package com.stupidbeauty.hxlauncher;

public interface InstallerMessageOrBuilder extends
    // @@protoc_insertion_point(interface_extends:com.stupidbeauty.hxlauncher.InstallerMessage)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <pre>
   *消息的时间戳。
   * </pre>
   *
   * <code>int64 timeStamp = 31;</code>
   */
  long getTimeStamp();
}
