// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: PackageItemAliasMapMessage.proto

package com.stupidbeauty.hxlauncher;

public final class PackageItemAliasMapMessageProtos {
  private PackageItemAliasMapMessageProtos() {}
  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistryLite registry) {
  }

  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistry registry) {
    registerAllExtensions(
        (com.google.protobuf.ExtensionRegistryLite) registry);
  }
  public interface PackageItemAliasMapMessageOrBuilder extends
      // @@protoc_insertion_point(interface_extends:com.stupidbeauty.hxlauncher.PackageItemAliasMapMessage)
      com.google.protobuf.MessageOrBuilder {

    /**
     * <pre>
     *映射数据体。
     * </pre>
     *
     * <code>repeated .com.stupidbeauty.hxlauncher.PackageItemAliasMapItemMessage map = 1;</code>
     */
    java.util.List<com.stupidbeauty.hxlauncher.PackageItemAliasMapItemMessageProtos.PackageItemAliasMapItemMessage> 
        getMapList();
    /**
     * <pre>
     *映射数据体。
     * </pre>
     *
     * <code>repeated .com.stupidbeauty.hxlauncher.PackageItemAliasMapItemMessage map = 1;</code>
     */
    com.stupidbeauty.hxlauncher.PackageItemAliasMapItemMessageProtos.PackageItemAliasMapItemMessage getMap(int index);
    /**
     * <pre>
     *映射数据体。
     * </pre>
     *
     * <code>repeated .com.stupidbeauty.hxlauncher.PackageItemAliasMapItemMessage map = 1;</code>
     */
    int getMapCount();
    /**
     * <pre>
     *映射数据体。
     * </pre>
     *
     * <code>repeated .com.stupidbeauty.hxlauncher.PackageItemAliasMapItemMessage map = 1;</code>
     */
    java.util.List<? extends com.stupidbeauty.hxlauncher.PackageItemAliasMapItemMessageProtos.PackageItemAliasMapItemMessageOrBuilder> 
        getMapOrBuilderList();
    /**
     * <pre>
     *映射数据体。
     * </pre>
     *
     * <code>repeated .com.stupidbeauty.hxlauncher.PackageItemAliasMapItemMessage map = 1;</code>
     */
    com.stupidbeauty.hxlauncher.PackageItemAliasMapItemMessageProtos.PackageItemAliasMapItemMessageOrBuilder getMapOrBuilder(
        int index);
  }
  /**
   * Protobuf type {@code com.stupidbeauty.hxlauncher.PackageItemAliasMapMessage}
   */
  public  static final class PackageItemAliasMapMessage extends
      com.google.protobuf.GeneratedMessageV3 implements
      // @@protoc_insertion_point(message_implements:com.stupidbeauty.hxlauncher.PackageItemAliasMapMessage)
      PackageItemAliasMapMessageOrBuilder {
  private static final long serialVersionUID = 0L;
    // Use PackageItemAliasMapMessage.newBuilder() to construct.
    private PackageItemAliasMapMessage(com.google.protobuf.GeneratedMessageV3.Builder<?> builder) {
      super(builder);
    }
    private PackageItemAliasMapMessage() {
      map_ = java.util.Collections.emptyList();
    }

    @java.lang.Override
    @SuppressWarnings({"unused"})
    protected java.lang.Object newInstance(
        UnusedPrivateParameter unused) {
      return new PackageItemAliasMapMessage();
    }

    @java.lang.Override
    public final com.google.protobuf.UnknownFieldSet
    getUnknownFields() {
      return this.unknownFields;
    }
    private PackageItemAliasMapMessage(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      this();
      if (extensionRegistry == null) {
        throw new java.lang.NullPointerException();
      }
      int mutable_bitField0_ = 0;
      com.google.protobuf.UnknownFieldSet.Builder unknownFields =
          com.google.protobuf.UnknownFieldSet.newBuilder();
      try {
        boolean done = false;
        while (!done) {
          int tag = input.readTag();
          switch (tag) {
            case 0:
              done = true;
              break;
            case 10: {
              if (!((mutable_bitField0_ & 0x00000001) != 0)) {
                map_ = new java.util.ArrayList<com.stupidbeauty.hxlauncher.PackageItemAliasMapItemMessageProtos.PackageItemAliasMapItemMessage>();
                mutable_bitField0_ |= 0x00000001;
              }
              map_.add(
                  input.readMessage(com.stupidbeauty.hxlauncher.PackageItemAliasMapItemMessageProtos.PackageItemAliasMapItemMessage.parser(), extensionRegistry));
              break;
            }
            default: {
              if (!parseUnknownField(
                  input, unknownFields, extensionRegistry, tag)) {
                done = true;
              }
              break;
            }
          }
        }
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        throw e.setUnfinishedMessage(this);
      } catch (java.io.IOException e) {
        throw new com.google.protobuf.InvalidProtocolBufferException(
            e).setUnfinishedMessage(this);
      } finally {
        if (((mutable_bitField0_ & 0x00000001) != 0)) {
          map_ = java.util.Collections.unmodifiableList(map_);
        }
        this.unknownFields = unknownFields.build();
        makeExtensionsImmutable();
      }
    }
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return com.stupidbeauty.hxlauncher.PackageItemAliasMapMessageProtos.internal_static_com_stupidbeauty_hxlauncher_PackageItemAliasMapMessage_descriptor;
    }

    @java.lang.Override
    protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return com.stupidbeauty.hxlauncher.PackageItemAliasMapMessageProtos.internal_static_com_stupidbeauty_hxlauncher_PackageItemAliasMapMessage_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              com.stupidbeauty.hxlauncher.PackageItemAliasMapMessageProtos.PackageItemAliasMapMessage.class, com.stupidbeauty.hxlauncher.PackageItemAliasMapMessageProtos.PackageItemAliasMapMessage.Builder.class);
    }

    public static final int MAP_FIELD_NUMBER = 1;
    private java.util.List<com.stupidbeauty.hxlauncher.PackageItemAliasMapItemMessageProtos.PackageItemAliasMapItemMessage> map_;
    /**
     * <pre>
     *映射数据体。
     * </pre>
     *
     * <code>repeated .com.stupidbeauty.hxlauncher.PackageItemAliasMapItemMessage map = 1;</code>
     */
    public java.util.List<com.stupidbeauty.hxlauncher.PackageItemAliasMapItemMessageProtos.PackageItemAliasMapItemMessage> getMapList() {
      return map_;
    }
    /**
     * <pre>
     *映射数据体。
     * </pre>
     *
     * <code>repeated .com.stupidbeauty.hxlauncher.PackageItemAliasMapItemMessage map = 1;</code>
     */
    public java.util.List<? extends com.stupidbeauty.hxlauncher.PackageItemAliasMapItemMessageProtos.PackageItemAliasMapItemMessageOrBuilder> 
        getMapOrBuilderList() {
      return map_;
    }
    /**
     * <pre>
     *映射数据体。
     * </pre>
     *
     * <code>repeated .com.stupidbeauty.hxlauncher.PackageItemAliasMapItemMessage map = 1;</code>
     */
    public int getMapCount() {
      return map_.size();
    }
    /**
     * <pre>
     *映射数据体。
     * </pre>
     *
     * <code>repeated .com.stupidbeauty.hxlauncher.PackageItemAliasMapItemMessage map = 1;</code>
     */
    public com.stupidbeauty.hxlauncher.PackageItemAliasMapItemMessageProtos.PackageItemAliasMapItemMessage getMap(int index) {
      return map_.get(index);
    }
    /**
     * <pre>
     *映射数据体。
     * </pre>
     *
     * <code>repeated .com.stupidbeauty.hxlauncher.PackageItemAliasMapItemMessage map = 1;</code>
     */
    public com.stupidbeauty.hxlauncher.PackageItemAliasMapItemMessageProtos.PackageItemAliasMapItemMessageOrBuilder getMapOrBuilder(
        int index) {
      return map_.get(index);
    }

    private byte memoizedIsInitialized = -1;
    @java.lang.Override
    public final boolean isInitialized() {
      byte isInitialized = memoizedIsInitialized;
      if (isInitialized == 1) return true;
      if (isInitialized == 0) return false;

      memoizedIsInitialized = 1;
      return true;
    }

    @java.lang.Override
    public void writeTo(com.google.protobuf.CodedOutputStream output)
                        throws java.io.IOException {
      for (int i = 0; i < map_.size(); i++) {
        output.writeMessage(1, map_.get(i));
      }
      unknownFields.writeTo(output);
    }

    @java.lang.Override
    public int getSerializedSize() {
      int size = memoizedSize;
      if (size != -1) return size;

      size = 0;
      for (int i = 0; i < map_.size(); i++) {
        size += com.google.protobuf.CodedOutputStream
          .computeMessageSize(1, map_.get(i));
      }
      size += unknownFields.getSerializedSize();
      memoizedSize = size;
      return size;
    }

    @java.lang.Override
    public boolean equals(final java.lang.Object obj) {
      if (obj == this) {
       return true;
      }
      if (!(obj instanceof com.stupidbeauty.hxlauncher.PackageItemAliasMapMessageProtos.PackageItemAliasMapMessage)) {
        return super.equals(obj);
      }
      com.stupidbeauty.hxlauncher.PackageItemAliasMapMessageProtos.PackageItemAliasMapMessage other = (com.stupidbeauty.hxlauncher.PackageItemAliasMapMessageProtos.PackageItemAliasMapMessage) obj;

      if (!getMapList()
          .equals(other.getMapList())) return false;
      if (!unknownFields.equals(other.unknownFields)) return false;
      return true;
    }

    @java.lang.Override
    public int hashCode() {
      if (memoizedHashCode != 0) {
        return memoizedHashCode;
      }
      int hash = 41;
      hash = (19 * hash) + getDescriptor().hashCode();
      if (getMapCount() > 0) {
        hash = (37 * hash) + MAP_FIELD_NUMBER;
        hash = (53 * hash) + getMapList().hashCode();
      }
      hash = (29 * hash) + unknownFields.hashCode();
      memoizedHashCode = hash;
      return hash;
    }

    public static com.stupidbeauty.hxlauncher.PackageItemAliasMapMessageProtos.PackageItemAliasMapMessage parseFrom(
        java.nio.ByteBuffer data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static com.stupidbeauty.hxlauncher.PackageItemAliasMapMessageProtos.PackageItemAliasMapMessage parseFrom(
        java.nio.ByteBuffer data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static com.stupidbeauty.hxlauncher.PackageItemAliasMapMessageProtos.PackageItemAliasMapMessage parseFrom(
        com.google.protobuf.ByteString data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static com.stupidbeauty.hxlauncher.PackageItemAliasMapMessageProtos.PackageItemAliasMapMessage parseFrom(
        com.google.protobuf.ByteString data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static com.stupidbeauty.hxlauncher.PackageItemAliasMapMessageProtos.PackageItemAliasMapMessage parseFrom(byte[] data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static com.stupidbeauty.hxlauncher.PackageItemAliasMapMessageProtos.PackageItemAliasMapMessage parseFrom(
        byte[] data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static com.stupidbeauty.hxlauncher.PackageItemAliasMapMessageProtos.PackageItemAliasMapMessage parseFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input);
    }
    public static com.stupidbeauty.hxlauncher.PackageItemAliasMapMessageProtos.PackageItemAliasMapMessage parseFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input, extensionRegistry);
    }
    public static com.stupidbeauty.hxlauncher.PackageItemAliasMapMessageProtos.PackageItemAliasMapMessage parseDelimitedFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseDelimitedWithIOException(PARSER, input);
    }
    public static com.stupidbeauty.hxlauncher.PackageItemAliasMapMessageProtos.PackageItemAliasMapMessage parseDelimitedFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseDelimitedWithIOException(PARSER, input, extensionRegistry);
    }
    public static com.stupidbeauty.hxlauncher.PackageItemAliasMapMessageProtos.PackageItemAliasMapMessage parseFrom(
        com.google.protobuf.CodedInputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input);
    }
    public static com.stupidbeauty.hxlauncher.PackageItemAliasMapMessageProtos.PackageItemAliasMapMessage parseFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input, extensionRegistry);
    }

    @java.lang.Override
    public Builder newBuilderForType() { return newBuilder(); }
    public static Builder newBuilder() {
      return DEFAULT_INSTANCE.toBuilder();
    }
    public static Builder newBuilder(com.stupidbeauty.hxlauncher.PackageItemAliasMapMessageProtos.PackageItemAliasMapMessage prototype) {
      return DEFAULT_INSTANCE.toBuilder().mergeFrom(prototype);
    }
    @java.lang.Override
    public Builder toBuilder() {
      return this == DEFAULT_INSTANCE
          ? new Builder() : new Builder().mergeFrom(this);
    }

    @java.lang.Override
    protected Builder newBuilderForType(
        com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
      Builder builder = new Builder(parent);
      return builder;
    }
    /**
     * Protobuf type {@code com.stupidbeauty.hxlauncher.PackageItemAliasMapMessage}
     */
    public static final class Builder extends
        com.google.protobuf.GeneratedMessageV3.Builder<Builder> implements
        // @@protoc_insertion_point(builder_implements:com.stupidbeauty.hxlauncher.PackageItemAliasMapMessage)
        com.stupidbeauty.hxlauncher.PackageItemAliasMapMessageProtos.PackageItemAliasMapMessageOrBuilder {
      public static final com.google.protobuf.Descriptors.Descriptor
          getDescriptor() {
        return com.stupidbeauty.hxlauncher.PackageItemAliasMapMessageProtos.internal_static_com_stupidbeauty_hxlauncher_PackageItemAliasMapMessage_descriptor;
      }

      @java.lang.Override
      protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
          internalGetFieldAccessorTable() {
        return com.stupidbeauty.hxlauncher.PackageItemAliasMapMessageProtos.internal_static_com_stupidbeauty_hxlauncher_PackageItemAliasMapMessage_fieldAccessorTable
            .ensureFieldAccessorsInitialized(
                com.stupidbeauty.hxlauncher.PackageItemAliasMapMessageProtos.PackageItemAliasMapMessage.class, com.stupidbeauty.hxlauncher.PackageItemAliasMapMessageProtos.PackageItemAliasMapMessage.Builder.class);
      }

      // Construct using com.stupidbeauty.hxlauncher.PackageItemAliasMapMessageProtos.PackageItemAliasMapMessage.newBuilder()
      private Builder() {
        maybeForceBuilderInitialization();
      }

      private Builder(
          com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
        super(parent);
        maybeForceBuilderInitialization();
      }
      private void maybeForceBuilderInitialization() {
        if (com.google.protobuf.GeneratedMessageV3
                .alwaysUseFieldBuilders) {
          getMapFieldBuilder();
        }
      }
      @java.lang.Override
      public Builder clear() {
        super.clear();
        if (mapBuilder_ == null) {
          map_ = java.util.Collections.emptyList();
          bitField0_ = (bitField0_ & ~0x00000001);
        } else {
          mapBuilder_.clear();
        }
        return this;
      }

      @java.lang.Override
      public com.google.protobuf.Descriptors.Descriptor
          getDescriptorForType() {
        return com.stupidbeauty.hxlauncher.PackageItemAliasMapMessageProtos.internal_static_com_stupidbeauty_hxlauncher_PackageItemAliasMapMessage_descriptor;
      }

      @java.lang.Override
      public com.stupidbeauty.hxlauncher.PackageItemAliasMapMessageProtos.PackageItemAliasMapMessage getDefaultInstanceForType() {
        return com.stupidbeauty.hxlauncher.PackageItemAliasMapMessageProtos.PackageItemAliasMapMessage.getDefaultInstance();
      }

      @java.lang.Override
      public com.stupidbeauty.hxlauncher.PackageItemAliasMapMessageProtos.PackageItemAliasMapMessage build() {
        com.stupidbeauty.hxlauncher.PackageItemAliasMapMessageProtos.PackageItemAliasMapMessage result = buildPartial();
        if (!result.isInitialized()) {
          throw newUninitializedMessageException(result);
        }
        return result;
      }

      @java.lang.Override
      public com.stupidbeauty.hxlauncher.PackageItemAliasMapMessageProtos.PackageItemAliasMapMessage buildPartial() {
        com.stupidbeauty.hxlauncher.PackageItemAliasMapMessageProtos.PackageItemAliasMapMessage result = new com.stupidbeauty.hxlauncher.PackageItemAliasMapMessageProtos.PackageItemAliasMapMessage(this);
        int from_bitField0_ = bitField0_;
        if (mapBuilder_ == null) {
          if (((bitField0_ & 0x00000001) != 0)) {
            map_ = java.util.Collections.unmodifiableList(map_);
            bitField0_ = (bitField0_ & ~0x00000001);
          }
          result.map_ = map_;
        } else {
          result.map_ = mapBuilder_.build();
        }
        onBuilt();
        return result;
      }

      @java.lang.Override
      public Builder clone() {
        return super.clone();
      }
      @java.lang.Override
      public Builder setField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          java.lang.Object value) {
        return super.setField(field, value);
      }
      @java.lang.Override
      public Builder clearField(
          com.google.protobuf.Descriptors.FieldDescriptor field) {
        return super.clearField(field);
      }
      @java.lang.Override
      public Builder clearOneof(
          com.google.protobuf.Descriptors.OneofDescriptor oneof) {
        return super.clearOneof(oneof);
      }
      @java.lang.Override
      public Builder setRepeatedField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          int index, java.lang.Object value) {
        return super.setRepeatedField(field, index, value);
      }
      @java.lang.Override
      public Builder addRepeatedField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          java.lang.Object value) {
        return super.addRepeatedField(field, value);
      }
      @java.lang.Override
      public Builder mergeFrom(com.google.protobuf.Message other) {
        if (other instanceof com.stupidbeauty.hxlauncher.PackageItemAliasMapMessageProtos.PackageItemAliasMapMessage) {
          return mergeFrom((com.stupidbeauty.hxlauncher.PackageItemAliasMapMessageProtos.PackageItemAliasMapMessage)other);
        } else {
          super.mergeFrom(other);
          return this;
        }
      }

      public Builder mergeFrom(com.stupidbeauty.hxlauncher.PackageItemAliasMapMessageProtos.PackageItemAliasMapMessage other) {
        if (other == com.stupidbeauty.hxlauncher.PackageItemAliasMapMessageProtos.PackageItemAliasMapMessage.getDefaultInstance()) return this;
        if (mapBuilder_ == null) {
          if (!other.map_.isEmpty()) {
            if (map_.isEmpty()) {
              map_ = other.map_;
              bitField0_ = (bitField0_ & ~0x00000001);
            } else {
              ensureMapIsMutable();
              map_.addAll(other.map_);
            }
            onChanged();
          }
        } else {
          if (!other.map_.isEmpty()) {
            if (mapBuilder_.isEmpty()) {
              mapBuilder_.dispose();
              mapBuilder_ = null;
              map_ = other.map_;
              bitField0_ = (bitField0_ & ~0x00000001);
              mapBuilder_ = 
                com.google.protobuf.GeneratedMessageV3.alwaysUseFieldBuilders ?
                   getMapFieldBuilder() : null;
            } else {
              mapBuilder_.addAllMessages(other.map_);
            }
          }
        }
        this.mergeUnknownFields(other.unknownFields);
        onChanged();
        return this;
      }

      @java.lang.Override
      public final boolean isInitialized() {
        return true;
      }

      @java.lang.Override
      public Builder mergeFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws java.io.IOException {
        com.stupidbeauty.hxlauncher.PackageItemAliasMapMessageProtos.PackageItemAliasMapMessage parsedMessage = null;
        try {
          parsedMessage = PARSER.parsePartialFrom(input, extensionRegistry);
        } catch (com.google.protobuf.InvalidProtocolBufferException e) {
          parsedMessage = (com.stupidbeauty.hxlauncher.PackageItemAliasMapMessageProtos.PackageItemAliasMapMessage) e.getUnfinishedMessage();
          throw e.unwrapIOException();
        } finally {
          if (parsedMessage != null) {
            mergeFrom(parsedMessage);
          }
        }
        return this;
      }
      private int bitField0_;

      private java.util.List<com.stupidbeauty.hxlauncher.PackageItemAliasMapItemMessageProtos.PackageItemAliasMapItemMessage> map_ =
        java.util.Collections.emptyList();
      private void ensureMapIsMutable() {
        if (!((bitField0_ & 0x00000001) != 0)) {
          map_ = new java.util.ArrayList<com.stupidbeauty.hxlauncher.PackageItemAliasMapItemMessageProtos.PackageItemAliasMapItemMessage>(map_);
          bitField0_ |= 0x00000001;
         }
      }

      private com.google.protobuf.RepeatedFieldBuilderV3<
          com.stupidbeauty.hxlauncher.PackageItemAliasMapItemMessageProtos.PackageItemAliasMapItemMessage, com.stupidbeauty.hxlauncher.PackageItemAliasMapItemMessageProtos.PackageItemAliasMapItemMessage.Builder, com.stupidbeauty.hxlauncher.PackageItemAliasMapItemMessageProtos.PackageItemAliasMapItemMessageOrBuilder> mapBuilder_;

      /**
       * <pre>
       *映射数据体。
       * </pre>
       *
       * <code>repeated .com.stupidbeauty.hxlauncher.PackageItemAliasMapItemMessage map = 1;</code>
       */
      public java.util.List<com.stupidbeauty.hxlauncher.PackageItemAliasMapItemMessageProtos.PackageItemAliasMapItemMessage> getMapList() {
        if (mapBuilder_ == null) {
          return java.util.Collections.unmodifiableList(map_);
        } else {
          return mapBuilder_.getMessageList();
        }
      }
      /**
       * <pre>
       *映射数据体。
       * </pre>
       *
       * <code>repeated .com.stupidbeauty.hxlauncher.PackageItemAliasMapItemMessage map = 1;</code>
       */
      public int getMapCount() {
        if (mapBuilder_ == null) {
          return map_.size();
        } else {
          return mapBuilder_.getCount();
        }
      }
      /**
       * <pre>
       *映射数据体。
       * </pre>
       *
       * <code>repeated .com.stupidbeauty.hxlauncher.PackageItemAliasMapItemMessage map = 1;</code>
       */
      public com.stupidbeauty.hxlauncher.PackageItemAliasMapItemMessageProtos.PackageItemAliasMapItemMessage getMap(int index) {
        if (mapBuilder_ == null) {
          return map_.get(index);
        } else {
          return mapBuilder_.getMessage(index);
        }
      }
      /**
       * <pre>
       *映射数据体。
       * </pre>
       *
       * <code>repeated .com.stupidbeauty.hxlauncher.PackageItemAliasMapItemMessage map = 1;</code>
       */
      public Builder setMap(
          int index, com.stupidbeauty.hxlauncher.PackageItemAliasMapItemMessageProtos.PackageItemAliasMapItemMessage value) {
        if (mapBuilder_ == null) {
          if (value == null) {
            throw new NullPointerException();
          }
          ensureMapIsMutable();
          map_.set(index, value);
          onChanged();
        } else {
          mapBuilder_.setMessage(index, value);
        }
        return this;
      }
      /**
       * <pre>
       *映射数据体。
       * </pre>
       *
       * <code>repeated .com.stupidbeauty.hxlauncher.PackageItemAliasMapItemMessage map = 1;</code>
       */
      public Builder setMap(
          int index, com.stupidbeauty.hxlauncher.PackageItemAliasMapItemMessageProtos.PackageItemAliasMapItemMessage.Builder builderForValue) {
        if (mapBuilder_ == null) {
          ensureMapIsMutable();
          map_.set(index, builderForValue.build());
          onChanged();
        } else {
          mapBuilder_.setMessage(index, builderForValue.build());
        }
        return this;
      }
      /**
       * <pre>
       *映射数据体。
       * </pre>
       *
       * <code>repeated .com.stupidbeauty.hxlauncher.PackageItemAliasMapItemMessage map = 1;</code>
       */
      public Builder addMap(com.stupidbeauty.hxlauncher.PackageItemAliasMapItemMessageProtos.PackageItemAliasMapItemMessage value) {
        if (mapBuilder_ == null) {
          if (value == null) {
            throw new NullPointerException();
          }
          ensureMapIsMutable();
          map_.add(value);
          onChanged();
        } else {
          mapBuilder_.addMessage(value);
        }
        return this;
      }
      /**
       * <pre>
       *映射数据体。
       * </pre>
       *
       * <code>repeated .com.stupidbeauty.hxlauncher.PackageItemAliasMapItemMessage map = 1;</code>
       */
      public Builder addMap(
          int index, com.stupidbeauty.hxlauncher.PackageItemAliasMapItemMessageProtos.PackageItemAliasMapItemMessage value) {
        if (mapBuilder_ == null) {
          if (value == null) {
            throw new NullPointerException();
          }
          ensureMapIsMutable();
          map_.add(index, value);
          onChanged();
        } else {
          mapBuilder_.addMessage(index, value);
        }
        return this;
      }
      /**
       * <pre>
       *映射数据体。
       * </pre>
       *
       * <code>repeated .com.stupidbeauty.hxlauncher.PackageItemAliasMapItemMessage map = 1;</code>
       */
      public Builder addMap(
          com.stupidbeauty.hxlauncher.PackageItemAliasMapItemMessageProtos.PackageItemAliasMapItemMessage.Builder builderForValue) {
        if (mapBuilder_ == null) {
          ensureMapIsMutable();
          map_.add(builderForValue.build());
          onChanged();
        } else {
          mapBuilder_.addMessage(builderForValue.build());
        }
        return this;
      }
      /**
       * <pre>
       *映射数据体。
       * </pre>
       *
       * <code>repeated .com.stupidbeauty.hxlauncher.PackageItemAliasMapItemMessage map = 1;</code>
       */
      public Builder addMap(
          int index, com.stupidbeauty.hxlauncher.PackageItemAliasMapItemMessageProtos.PackageItemAliasMapItemMessage.Builder builderForValue) {
        if (mapBuilder_ == null) {
          ensureMapIsMutable();
          map_.add(index, builderForValue.build());
          onChanged();
        } else {
          mapBuilder_.addMessage(index, builderForValue.build());
        }
        return this;
      }
      /**
       * <pre>
       *映射数据体。
       * </pre>
       *
       * <code>repeated .com.stupidbeauty.hxlauncher.PackageItemAliasMapItemMessage map = 1;</code>
       */
      public Builder addAllMap(
          java.lang.Iterable<? extends com.stupidbeauty.hxlauncher.PackageItemAliasMapItemMessageProtos.PackageItemAliasMapItemMessage> values) {
        if (mapBuilder_ == null) {
          ensureMapIsMutable();
          com.google.protobuf.AbstractMessageLite.Builder.addAll(
              values, map_);
          onChanged();
        } else {
          mapBuilder_.addAllMessages(values);
        }
        return this;
      }
      /**
       * <pre>
       *映射数据体。
       * </pre>
       *
       * <code>repeated .com.stupidbeauty.hxlauncher.PackageItemAliasMapItemMessage map = 1;</code>
       */
      public Builder clearMap() {
        if (mapBuilder_ == null) {
          map_ = java.util.Collections.emptyList();
          bitField0_ = (bitField0_ & ~0x00000001);
          onChanged();
        } else {
          mapBuilder_.clear();
        }
        return this;
      }
      /**
       * <pre>
       *映射数据体。
       * </pre>
       *
       * <code>repeated .com.stupidbeauty.hxlauncher.PackageItemAliasMapItemMessage map = 1;</code>
       */
      public Builder removeMap(int index) {
        if (mapBuilder_ == null) {
          ensureMapIsMutable();
          map_.remove(index);
          onChanged();
        } else {
          mapBuilder_.remove(index);
        }
        return this;
      }
      /**
       * <pre>
       *映射数据体。
       * </pre>
       *
       * <code>repeated .com.stupidbeauty.hxlauncher.PackageItemAliasMapItemMessage map = 1;</code>
       */
      public com.stupidbeauty.hxlauncher.PackageItemAliasMapItemMessageProtos.PackageItemAliasMapItemMessage.Builder getMapBuilder(
          int index) {
        return getMapFieldBuilder().getBuilder(index);
      }
      /**
       * <pre>
       *映射数据体。
       * </pre>
       *
       * <code>repeated .com.stupidbeauty.hxlauncher.PackageItemAliasMapItemMessage map = 1;</code>
       */
      public com.stupidbeauty.hxlauncher.PackageItemAliasMapItemMessageProtos.PackageItemAliasMapItemMessageOrBuilder getMapOrBuilder(
          int index) {
        if (mapBuilder_ == null) {
          return map_.get(index);  } else {
          return mapBuilder_.getMessageOrBuilder(index);
        }
      }
      /**
       * <pre>
       *映射数据体。
       * </pre>
       *
       * <code>repeated .com.stupidbeauty.hxlauncher.PackageItemAliasMapItemMessage map = 1;</code>
       */
      public java.util.List<? extends com.stupidbeauty.hxlauncher.PackageItemAliasMapItemMessageProtos.PackageItemAliasMapItemMessageOrBuilder> 
           getMapOrBuilderList() {
        if (mapBuilder_ != null) {
          return mapBuilder_.getMessageOrBuilderList();
        } else {
          return java.util.Collections.unmodifiableList(map_);
        }
      }
      /**
       * <pre>
       *映射数据体。
       * </pre>
       *
       * <code>repeated .com.stupidbeauty.hxlauncher.PackageItemAliasMapItemMessage map = 1;</code>
       */
      public com.stupidbeauty.hxlauncher.PackageItemAliasMapItemMessageProtos.PackageItemAliasMapItemMessage.Builder addMapBuilder() {
        return getMapFieldBuilder().addBuilder(
            com.stupidbeauty.hxlauncher.PackageItemAliasMapItemMessageProtos.PackageItemAliasMapItemMessage.getDefaultInstance());
      }
      /**
       * <pre>
       *映射数据体。
       * </pre>
       *
       * <code>repeated .com.stupidbeauty.hxlauncher.PackageItemAliasMapItemMessage map = 1;</code>
       */
      public com.stupidbeauty.hxlauncher.PackageItemAliasMapItemMessageProtos.PackageItemAliasMapItemMessage.Builder addMapBuilder(
          int index) {
        return getMapFieldBuilder().addBuilder(
            index, com.stupidbeauty.hxlauncher.PackageItemAliasMapItemMessageProtos.PackageItemAliasMapItemMessage.getDefaultInstance());
      }
      /**
       * <pre>
       *映射数据体。
       * </pre>
       *
       * <code>repeated .com.stupidbeauty.hxlauncher.PackageItemAliasMapItemMessage map = 1;</code>
       */
      public java.util.List<com.stupidbeauty.hxlauncher.PackageItemAliasMapItemMessageProtos.PackageItemAliasMapItemMessage.Builder> 
           getMapBuilderList() {
        return getMapFieldBuilder().getBuilderList();
      }
      private com.google.protobuf.RepeatedFieldBuilderV3<
          com.stupidbeauty.hxlauncher.PackageItemAliasMapItemMessageProtos.PackageItemAliasMapItemMessage, com.stupidbeauty.hxlauncher.PackageItemAliasMapItemMessageProtos.PackageItemAliasMapItemMessage.Builder, com.stupidbeauty.hxlauncher.PackageItemAliasMapItemMessageProtos.PackageItemAliasMapItemMessageOrBuilder> 
          getMapFieldBuilder() {
        if (mapBuilder_ == null) {
          mapBuilder_ = new com.google.protobuf.RepeatedFieldBuilderV3<
              com.stupidbeauty.hxlauncher.PackageItemAliasMapItemMessageProtos.PackageItemAliasMapItemMessage, com.stupidbeauty.hxlauncher.PackageItemAliasMapItemMessageProtos.PackageItemAliasMapItemMessage.Builder, com.stupidbeauty.hxlauncher.PackageItemAliasMapItemMessageProtos.PackageItemAliasMapItemMessageOrBuilder>(
                  map_,
                  ((bitField0_ & 0x00000001) != 0),
                  getParentForChildren(),
                  isClean());
          map_ = null;
        }
        return mapBuilder_;
      }
      @java.lang.Override
      public final Builder setUnknownFields(
          final com.google.protobuf.UnknownFieldSet unknownFields) {
        return super.setUnknownFields(unknownFields);
      }

      @java.lang.Override
      public final Builder mergeUnknownFields(
          final com.google.protobuf.UnknownFieldSet unknownFields) {
        return super.mergeUnknownFields(unknownFields);
      }


      // @@protoc_insertion_point(builder_scope:com.stupidbeauty.hxlauncher.PackageItemAliasMapMessage)
    }

    // @@protoc_insertion_point(class_scope:com.stupidbeauty.hxlauncher.PackageItemAliasMapMessage)
    private static final com.stupidbeauty.hxlauncher.PackageItemAliasMapMessageProtos.PackageItemAliasMapMessage DEFAULT_INSTANCE;
    static {
      DEFAULT_INSTANCE = new com.stupidbeauty.hxlauncher.PackageItemAliasMapMessageProtos.PackageItemAliasMapMessage();
    }

    public static com.stupidbeauty.hxlauncher.PackageItemAliasMapMessageProtos.PackageItemAliasMapMessage getDefaultInstance() {
      return DEFAULT_INSTANCE;
    }

    private static final com.google.protobuf.Parser<PackageItemAliasMapMessage>
        PARSER = new com.google.protobuf.AbstractParser<PackageItemAliasMapMessage>() {
      @java.lang.Override
      public PackageItemAliasMapMessage parsePartialFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws com.google.protobuf.InvalidProtocolBufferException {
        return new PackageItemAliasMapMessage(input, extensionRegistry);
      }
    };

    public static com.google.protobuf.Parser<PackageItemAliasMapMessage> parser() {
      return PARSER;
    }

    @java.lang.Override
    public com.google.protobuf.Parser<PackageItemAliasMapMessage> getParserForType() {
      return PARSER;
    }

    @java.lang.Override
    public com.stupidbeauty.hxlauncher.PackageItemAliasMapMessageProtos.PackageItemAliasMapMessage getDefaultInstanceForType() {
      return DEFAULT_INSTANCE;
    }

  }

  private static final com.google.protobuf.Descriptors.Descriptor
    internal_static_com_stupidbeauty_hxlauncher_PackageItemAliasMapMessage_descriptor;
  private static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_com_stupidbeauty_hxlauncher_PackageItemAliasMapMessage_fieldAccessorTable;

  public static com.google.protobuf.Descriptors.FileDescriptor
      getDescriptor() {
    return descriptor;
  }
  private static  com.google.protobuf.Descriptors.FileDescriptor
      descriptor;
  static {
    java.lang.String[] descriptorData = {
      "\n PackageItemAliasMapMessage.proto\022\033com." +
      "stupidbeauty.hxlauncher\032$PackageItemAlia" +
      "sMapItemMessage.proto\"f\n\032PackageItemAlia" +
      "sMapMessage\022H\n\003map\030\001 \003(\0132;.com.stupidbea" +
      "uty.hxlauncher.PackageItemAliasMapItemMe" +
      "ssageB?\n\033com.stupidbeauty.hxlauncherB Pa" +
      "ckageItemAliasMapMessageProtosb\006proto3"
    };
    descriptor = com.google.protobuf.Descriptors.FileDescriptor
      .internalBuildGeneratedFileFrom(descriptorData,
        new com.google.protobuf.Descriptors.FileDescriptor[] {
          com.stupidbeauty.hxlauncher.PackageItemAliasMapItemMessageProtos.getDescriptor(),
        });
    internal_static_com_stupidbeauty_hxlauncher_PackageItemAliasMapMessage_descriptor =
      getDescriptor().getMessageTypes().get(0);
    internal_static_com_stupidbeauty_hxlauncher_PackageItemAliasMapMessage_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_com_stupidbeauty_hxlauncher_PackageItemAliasMapMessage_descriptor,
        new java.lang.String[] { "Map", });
    com.stupidbeauty.hxlauncher.PackageItemAliasMapItemMessageProtos.getDescriptor();
  }

  // @@protoc_insertion_point(outer_class_scope)
}
