// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: ReplyHeader.proto

package com.stupidbeauty.hxlauncher;

public final class ReplyHeaderProtos {
  private ReplyHeaderProtos() {}
  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistryLite registry) {
  }

  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistry registry) {
    registerAllExtensions(
        (com.google.protobuf.ExtensionRegistryLite) registry);
  }
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_com_stupidbeauty_hxlauncher_ReplyHeader_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_com_stupidbeauty_hxlauncher_ReplyHeader_fieldAccessorTable;

  public static com.google.protobuf.Descriptors.FileDescriptor
      getDescriptor() {
    return descriptor;
  }
  private static  com.google.protobuf.Descriptors.FileDescriptor
      descriptor;
  static {
    java.lang.String[] descriptorData = {
      "\n\021ReplyHeader.proto\022\033com.stupidbeauty.hx" +
      "launcher\"*\n\013ReplyHeader\022\013\n\003ret\030\001 \001(\005\022\016\n\006" +
      "errMsg\030\002 \001(\tB2\n\033com.stupidbeauty.hxlaunc" +
      "herB\021ReplyHeaderProtosP\001b\006proto3"
    };
    descriptor = com.google.protobuf.Descriptors.FileDescriptor
      .internalBuildGeneratedFileFrom(descriptorData,
        new com.google.protobuf.Descriptors.FileDescriptor[] {
        });
    internal_static_com_stupidbeauty_hxlauncher_ReplyHeader_descriptor =
      getDescriptor().getMessageTypes().get(0);
    internal_static_com_stupidbeauty_hxlauncher_ReplyHeader_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_com_stupidbeauty_hxlauncher_ReplyHeader_descriptor,
        new java.lang.String[] { "Ret", "ErrMsg", });
  }

  // @@protoc_insertion_point(outer_class_scope)
}
