// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: ReplyHeader.proto

package com.stupidbeauty.hxlauncher;

public interface ReplyHeaderOrBuilder extends
    // @@protoc_insertion_point(interface_extends:com.stupidbeauty.hxlauncher.ReplyHeader)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <pre>
   * 调用结果返回码, 0-成功 其他-失败,发生错误
   * </pre>
   *
   * <code>int32 ret = 1;</code>
   * @return The ret.
   */
  int getRet();

  /**
   * <pre>
   * 调用结果说明, OK-成功
   * </pre>
   *
   * <code>string errMsg = 2;</code>
   * @return The errMsg.
   */
  java.lang.String getErrMsg();
  /**
   * <pre>
   * 调用结果说明, OK-成功
   * </pre>
   *
   * <code>string errMsg = 2;</code>
   * @return The bytes for errMsg.
   */
  com.google.protobuf.ByteString
      getErrMsgBytes();
}
