// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: ReportErrorCodeReq.proto

package com.stupidbeauty.hxlauncher;

/**
 * Protobuf type {@code com.stupidbeauty.hxlauncher.ReportErrorCodeReq}
 */
public  final class ReportErrorCodeReq extends
    com.google.protobuf.GeneratedMessageV3 implements
    // @@protoc_insertion_point(message_implements:com.stupidbeauty.hxlauncher.ReportErrorCodeReq)
    ReportErrorCodeReqOrBuilder {
private static final long serialVersionUID = 0L;
  // Use ReportErrorCodeReq.newBuilder() to construct.
  private ReportErrorCodeReq(com.google.protobuf.GeneratedMessageV3.Builder<?> builder) {
    super(builder);
  }
  private ReportErrorCodeReq() {
    errorMessage_ = "";
    errorDetails_ = "";
    severityLevel_ = "";
  }

  @java.lang.Override
  @SuppressWarnings({"unused"})
  protected java.lang.Object newInstance(
      UnusedPrivateParameter unused) {
    return new ReportErrorCodeReq();
  }

  @java.lang.Override
  public final com.google.protobuf.UnknownFieldSet
  getUnknownFields() {
    return this.unknownFields;
  }
  private ReportErrorCodeReq(
      com.google.protobuf.CodedInputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    this();
    if (extensionRegistry == null) {
      throw new java.lang.NullPointerException();
    }
    com.google.protobuf.UnknownFieldSet.Builder unknownFields =
        com.google.protobuf.UnknownFieldSet.newBuilder();
    try {
      boolean done = false;
      while (!done) {
        int tag = input.readTag();
        switch (tag) {
          case 0:
            done = true;
            break;
          case 8: {

            errorCode_ = input.readInt32();
            break;
          }
          case 18: {
            java.lang.String s = input.readStringRequireUtf8();

            errorMessage_ = s;
            break;
          }
          case 26: {
            java.lang.String s = input.readStringRequireUtf8();

            errorDetails_ = s;
            break;
          }
          case 34: {
            java.lang.String s = input.readStringRequireUtf8();

            severityLevel_ = s;
            break;
          }
          default: {
            if (!parseUnknownField(
                input, unknownFields, extensionRegistry, tag)) {
              done = true;
            }
            break;
          }
        }
      }
    } catch (com.google.protobuf.InvalidProtocolBufferException e) {
      throw e.setUnfinishedMessage(this);
    } catch (java.io.IOException e) {
      throw new com.google.protobuf.InvalidProtocolBufferException(
          e).setUnfinishedMessage(this);
    } finally {
      this.unknownFields = unknownFields.build();
      makeExtensionsImmutable();
    }
  }
  public static final com.google.protobuf.Descriptors.Descriptor
      getDescriptor() {
    return com.stupidbeauty.hxlauncher.ReportErrorCodeReqProtos.internal_static_com_stupidbeauty_hxlauncher_ReportErrorCodeReq_descriptor;
  }

  @java.lang.Override
  protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internalGetFieldAccessorTable() {
    return com.stupidbeauty.hxlauncher.ReportErrorCodeReqProtos.internal_static_com_stupidbeauty_hxlauncher_ReportErrorCodeReq_fieldAccessorTable
        .ensureFieldAccessorsInitialized(
            com.stupidbeauty.hxlauncher.ReportErrorCodeReq.class, com.stupidbeauty.hxlauncher.ReportErrorCodeReq.Builder.class);
  }

  public static final int ERRORCODE_FIELD_NUMBER = 1;
  private int errorCode_;
  /**
   * <pre>
   *错误码。
   * </pre>
   *
   * <code>int32 errorCode = 1;</code>
   * @return The errorCode.
   */
  public int getErrorCode() {
    return errorCode_;
  }

  public static final int ERRORMESSAGE_FIELD_NUMBER = 2;
  private volatile java.lang.Object errorMessage_;
  /**
   * <pre>
   *错误消息文字内容。
   * </pre>
   *
   * <code>string errorMessage = 2;</code>
   * @return The errorMessage.
   */
  public java.lang.String getErrorMessage() {
    java.lang.Object ref = errorMessage_;
    if (ref instanceof java.lang.String) {
      return (java.lang.String) ref;
    } else {
      com.google.protobuf.ByteString bs = 
          (com.google.protobuf.ByteString) ref;
      java.lang.String s = bs.toStringUtf8();
      errorMessage_ = s;
      return s;
    }
  }
  /**
   * <pre>
   *错误消息文字内容。
   * </pre>
   *
   * <code>string errorMessage = 2;</code>
   * @return The bytes for errorMessage.
   */
  public com.google.protobuf.ByteString
      getErrorMessageBytes() {
    java.lang.Object ref = errorMessage_;
    if (ref instanceof java.lang.String) {
      com.google.protobuf.ByteString b = 
          com.google.protobuf.ByteString.copyFromUtf8(
              (java.lang.String) ref);
      errorMessage_ = b;
      return b;
    } else {
      return (com.google.protobuf.ByteString) ref;
    }
  }

  public static final int ERRORDETAILS_FIELD_NUMBER = 3;
  private volatile java.lang.Object errorDetails_;
  /**
   * <pre>
   *错误消息详情。
   * </pre>
   *
   * <code>string errorDetails = 3;</code>
   * @return The errorDetails.
   */
  public java.lang.String getErrorDetails() {
    java.lang.Object ref = errorDetails_;
    if (ref instanceof java.lang.String) {
      return (java.lang.String) ref;
    } else {
      com.google.protobuf.ByteString bs = 
          (com.google.protobuf.ByteString) ref;
      java.lang.String s = bs.toStringUtf8();
      errorDetails_ = s;
      return s;
    }
  }
  /**
   * <pre>
   *错误消息详情。
   * </pre>
   *
   * <code>string errorDetails = 3;</code>
   * @return The bytes for errorDetails.
   */
  public com.google.protobuf.ByteString
      getErrorDetailsBytes() {
    java.lang.Object ref = errorDetails_;
    if (ref instanceof java.lang.String) {
      com.google.protobuf.ByteString b = 
          com.google.protobuf.ByteString.copyFromUtf8(
              (java.lang.String) ref);
      errorDetails_ = b;
      return b;
    } else {
      return (com.google.protobuf.ByteString) ref;
    }
  }

  public static final int SEVERITYLEVEL_FIELD_NUMBER = 4;
  private volatile java.lang.Object severityLevel_;
  /**
   * <pre>
   *严重级别。
   * </pre>
   *
   * <code>string severityLevel = 4;</code>
   * @return The severityLevel.
   */
  public java.lang.String getSeverityLevel() {
    java.lang.Object ref = severityLevel_;
    if (ref instanceof java.lang.String) {
      return (java.lang.String) ref;
    } else {
      com.google.protobuf.ByteString bs = 
          (com.google.protobuf.ByteString) ref;
      java.lang.String s = bs.toStringUtf8();
      severityLevel_ = s;
      return s;
    }
  }
  /**
   * <pre>
   *严重级别。
   * </pre>
   *
   * <code>string severityLevel = 4;</code>
   * @return The bytes for severityLevel.
   */
  public com.google.protobuf.ByteString
      getSeverityLevelBytes() {
    java.lang.Object ref = severityLevel_;
    if (ref instanceof java.lang.String) {
      com.google.protobuf.ByteString b = 
          com.google.protobuf.ByteString.copyFromUtf8(
              (java.lang.String) ref);
      severityLevel_ = b;
      return b;
    } else {
      return (com.google.protobuf.ByteString) ref;
    }
  }

  private byte memoizedIsInitialized = -1;
  @java.lang.Override
  public final boolean isInitialized() {
    byte isInitialized = memoizedIsInitialized;
    if (isInitialized == 1) return true;
    if (isInitialized == 0) return false;

    memoizedIsInitialized = 1;
    return true;
  }

  @java.lang.Override
  public void writeTo(com.google.protobuf.CodedOutputStream output)
                      throws java.io.IOException {
    if (errorCode_ != 0) {
      output.writeInt32(1, errorCode_);
    }
    if (!getErrorMessageBytes().isEmpty()) {
      com.google.protobuf.GeneratedMessageV3.writeString(output, 2, errorMessage_);
    }
    if (!getErrorDetailsBytes().isEmpty()) {
      com.google.protobuf.GeneratedMessageV3.writeString(output, 3, errorDetails_);
    }
    if (!getSeverityLevelBytes().isEmpty()) {
      com.google.protobuf.GeneratedMessageV3.writeString(output, 4, severityLevel_);
    }
    unknownFields.writeTo(output);
  }

  @java.lang.Override
  public int getSerializedSize() {
    int size = memoizedSize;
    if (size != -1) return size;

    size = 0;
    if (errorCode_ != 0) {
      size += com.google.protobuf.CodedOutputStream
        .computeInt32Size(1, errorCode_);
    }
    if (!getErrorMessageBytes().isEmpty()) {
      size += com.google.protobuf.GeneratedMessageV3.computeStringSize(2, errorMessage_);
    }
    if (!getErrorDetailsBytes().isEmpty()) {
      size += com.google.protobuf.GeneratedMessageV3.computeStringSize(3, errorDetails_);
    }
    if (!getSeverityLevelBytes().isEmpty()) {
      size += com.google.protobuf.GeneratedMessageV3.computeStringSize(4, severityLevel_);
    }
    size += unknownFields.getSerializedSize();
    memoizedSize = size;
    return size;
  }

  @java.lang.Override
  public boolean equals(final java.lang.Object obj) {
    if (obj == this) {
     return true;
    }
    if (!(obj instanceof com.stupidbeauty.hxlauncher.ReportErrorCodeReq)) {
      return super.equals(obj);
    }
    com.stupidbeauty.hxlauncher.ReportErrorCodeReq other = (com.stupidbeauty.hxlauncher.ReportErrorCodeReq) obj;

    if (getErrorCode()
        != other.getErrorCode()) return false;
    if (!getErrorMessage()
        .equals(other.getErrorMessage())) return false;
    if (!getErrorDetails()
        .equals(other.getErrorDetails())) return false;
    if (!getSeverityLevel()
        .equals(other.getSeverityLevel())) return false;
    if (!unknownFields.equals(other.unknownFields)) return false;
    return true;
  }

  @java.lang.Override
  public int hashCode() {
    if (memoizedHashCode != 0) {
      return memoizedHashCode;
    }
    int hash = 41;
    hash = (19 * hash) + getDescriptor().hashCode();
    hash = (37 * hash) + ERRORCODE_FIELD_NUMBER;
    hash = (53 * hash) + getErrorCode();
    hash = (37 * hash) + ERRORMESSAGE_FIELD_NUMBER;
    hash = (53 * hash) + getErrorMessage().hashCode();
    hash = (37 * hash) + ERRORDETAILS_FIELD_NUMBER;
    hash = (53 * hash) + getErrorDetails().hashCode();
    hash = (37 * hash) + SEVERITYLEVEL_FIELD_NUMBER;
    hash = (53 * hash) + getSeverityLevel().hashCode();
    hash = (29 * hash) + unknownFields.hashCode();
    memoizedHashCode = hash;
    return hash;
  }

  public static com.stupidbeauty.hxlauncher.ReportErrorCodeReq parseFrom(
      java.nio.ByteBuffer data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static com.stupidbeauty.hxlauncher.ReportErrorCodeReq parseFrom(
      java.nio.ByteBuffer data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static com.stupidbeauty.hxlauncher.ReportErrorCodeReq parseFrom(
      com.google.protobuf.ByteString data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static com.stupidbeauty.hxlauncher.ReportErrorCodeReq parseFrom(
      com.google.protobuf.ByteString data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static com.stupidbeauty.hxlauncher.ReportErrorCodeReq parseFrom(byte[] data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static com.stupidbeauty.hxlauncher.ReportErrorCodeReq parseFrom(
      byte[] data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static com.stupidbeauty.hxlauncher.ReportErrorCodeReq parseFrom(java.io.InputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input);
  }
  public static com.stupidbeauty.hxlauncher.ReportErrorCodeReq parseFrom(
      java.io.InputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input, extensionRegistry);
  }
  public static com.stupidbeauty.hxlauncher.ReportErrorCodeReq parseDelimitedFrom(java.io.InputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseDelimitedWithIOException(PARSER, input);
  }
  public static com.stupidbeauty.hxlauncher.ReportErrorCodeReq parseDelimitedFrom(
      java.io.InputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseDelimitedWithIOException(PARSER, input, extensionRegistry);
  }
  public static com.stupidbeauty.hxlauncher.ReportErrorCodeReq parseFrom(
      com.google.protobuf.CodedInputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input);
  }
  public static com.stupidbeauty.hxlauncher.ReportErrorCodeReq parseFrom(
      com.google.protobuf.CodedInputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input, extensionRegistry);
  }

  @java.lang.Override
  public Builder newBuilderForType() { return newBuilder(); }
  public static Builder newBuilder() {
    return DEFAULT_INSTANCE.toBuilder();
  }
  public static Builder newBuilder(com.stupidbeauty.hxlauncher.ReportErrorCodeReq prototype) {
    return DEFAULT_INSTANCE.toBuilder().mergeFrom(prototype);
  }
  @java.lang.Override
  public Builder toBuilder() {
    return this == DEFAULT_INSTANCE
        ? new Builder() : new Builder().mergeFrom(this);
  }

  @java.lang.Override
  protected Builder newBuilderForType(
      com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
    Builder builder = new Builder(parent);
    return builder;
  }
  /**
   * Protobuf type {@code com.stupidbeauty.hxlauncher.ReportErrorCodeReq}
   */
  public static final class Builder extends
      com.google.protobuf.GeneratedMessageV3.Builder<Builder> implements
      // @@protoc_insertion_point(builder_implements:com.stupidbeauty.hxlauncher.ReportErrorCodeReq)
      com.stupidbeauty.hxlauncher.ReportErrorCodeReqOrBuilder {
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return com.stupidbeauty.hxlauncher.ReportErrorCodeReqProtos.internal_static_com_stupidbeauty_hxlauncher_ReportErrorCodeReq_descriptor;
    }

    @java.lang.Override
    protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return com.stupidbeauty.hxlauncher.ReportErrorCodeReqProtos.internal_static_com_stupidbeauty_hxlauncher_ReportErrorCodeReq_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              com.stupidbeauty.hxlauncher.ReportErrorCodeReq.class, com.stupidbeauty.hxlauncher.ReportErrorCodeReq.Builder.class);
    }

    // Construct using com.stupidbeauty.hxlauncher.ReportErrorCodeReq.newBuilder()
    private Builder() {
      maybeForceBuilderInitialization();
    }

    private Builder(
        com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
      super(parent);
      maybeForceBuilderInitialization();
    }
    private void maybeForceBuilderInitialization() {
      if (com.google.protobuf.GeneratedMessageV3
              .alwaysUseFieldBuilders) {
      }
    }
    @java.lang.Override
    public Builder clear() {
      super.clear();
      errorCode_ = 0;

      errorMessage_ = "";

      errorDetails_ = "";

      severityLevel_ = "";

      return this;
    }

    @java.lang.Override
    public com.google.protobuf.Descriptors.Descriptor
        getDescriptorForType() {
      return com.stupidbeauty.hxlauncher.ReportErrorCodeReqProtos.internal_static_com_stupidbeauty_hxlauncher_ReportErrorCodeReq_descriptor;
    }

    @java.lang.Override
    public com.stupidbeauty.hxlauncher.ReportErrorCodeReq getDefaultInstanceForType() {
      return com.stupidbeauty.hxlauncher.ReportErrorCodeReq.getDefaultInstance();
    }

    @java.lang.Override
    public com.stupidbeauty.hxlauncher.ReportErrorCodeReq build() {
      com.stupidbeauty.hxlauncher.ReportErrorCodeReq result = buildPartial();
      if (!result.isInitialized()) {
        throw newUninitializedMessageException(result);
      }
      return result;
    }

    @java.lang.Override
    public com.stupidbeauty.hxlauncher.ReportErrorCodeReq buildPartial() {
      com.stupidbeauty.hxlauncher.ReportErrorCodeReq result = new com.stupidbeauty.hxlauncher.ReportErrorCodeReq(this);
      result.errorCode_ = errorCode_;
      result.errorMessage_ = errorMessage_;
      result.errorDetails_ = errorDetails_;
      result.severityLevel_ = severityLevel_;
      onBuilt();
      return result;
    }

    @java.lang.Override
    public Builder clone() {
      return super.clone();
    }
    @java.lang.Override
    public Builder setField(
        com.google.protobuf.Descriptors.FieldDescriptor field,
        java.lang.Object value) {
      return super.setField(field, value);
    }
    @java.lang.Override
    public Builder clearField(
        com.google.protobuf.Descriptors.FieldDescriptor field) {
      return super.clearField(field);
    }
    @java.lang.Override
    public Builder clearOneof(
        com.google.protobuf.Descriptors.OneofDescriptor oneof) {
      return super.clearOneof(oneof);
    }
    @java.lang.Override
    public Builder setRepeatedField(
        com.google.protobuf.Descriptors.FieldDescriptor field,
        int index, java.lang.Object value) {
      return super.setRepeatedField(field, index, value);
    }
    @java.lang.Override
    public Builder addRepeatedField(
        com.google.protobuf.Descriptors.FieldDescriptor field,
        java.lang.Object value) {
      return super.addRepeatedField(field, value);
    }
    @java.lang.Override
    public Builder mergeFrom(com.google.protobuf.Message other) {
      if (other instanceof com.stupidbeauty.hxlauncher.ReportErrorCodeReq) {
        return mergeFrom((com.stupidbeauty.hxlauncher.ReportErrorCodeReq)other);
      } else {
        super.mergeFrom(other);
        return this;
      }
    }

    public Builder mergeFrom(com.stupidbeauty.hxlauncher.ReportErrorCodeReq other) {
      if (other == com.stupidbeauty.hxlauncher.ReportErrorCodeReq.getDefaultInstance()) return this;
      if (other.getErrorCode() != 0) {
        setErrorCode(other.getErrorCode());
      }
      if (!other.getErrorMessage().isEmpty()) {
        errorMessage_ = other.errorMessage_;
        onChanged();
      }
      if (!other.getErrorDetails().isEmpty()) {
        errorDetails_ = other.errorDetails_;
        onChanged();
      }
      if (!other.getSeverityLevel().isEmpty()) {
        severityLevel_ = other.severityLevel_;
        onChanged();
      }
      this.mergeUnknownFields(other.unknownFields);
      onChanged();
      return this;
    }

    @java.lang.Override
    public final boolean isInitialized() {
      return true;
    }

    @java.lang.Override
    public Builder mergeFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      com.stupidbeauty.hxlauncher.ReportErrorCodeReq parsedMessage = null;
      try {
        parsedMessage = PARSER.parsePartialFrom(input, extensionRegistry);
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        parsedMessage = (com.stupidbeauty.hxlauncher.ReportErrorCodeReq) e.getUnfinishedMessage();
        throw e.unwrapIOException();
      } finally {
        if (parsedMessage != null) {
          mergeFrom(parsedMessage);
        }
      }
      return this;
    }

    private int errorCode_ ;
    /**
     * <pre>
     *错误码。
     * </pre>
     *
     * <code>int32 errorCode = 1;</code>
     * @return The errorCode.
     */
    public int getErrorCode() {
      return errorCode_;
    }
    /**
     * <pre>
     *错误码。
     * </pre>
     *
     * <code>int32 errorCode = 1;</code>
     * @param value The errorCode to set.
     * @return This builder for chaining.
     */
    public Builder setErrorCode(int value) {
      
      errorCode_ = value;
      onChanged();
      return this;
    }
    /**
     * <pre>
     *错误码。
     * </pre>
     *
     * <code>int32 errorCode = 1;</code>
     * @return This builder for chaining.
     */
    public Builder clearErrorCode() {
      
      errorCode_ = 0;
      onChanged();
      return this;
    }

    private java.lang.Object errorMessage_ = "";
    /**
     * <pre>
     *错误消息文字内容。
     * </pre>
     *
     * <code>string errorMessage = 2;</code>
     * @return The errorMessage.
     */
    public java.lang.String getErrorMessage() {
      java.lang.Object ref = errorMessage_;
      if (!(ref instanceof java.lang.String)) {
        com.google.protobuf.ByteString bs =
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        errorMessage_ = s;
        return s;
      } else {
        return (java.lang.String) ref;
      }
    }
    /**
     * <pre>
     *错误消息文字内容。
     * </pre>
     *
     * <code>string errorMessage = 2;</code>
     * @return The bytes for errorMessage.
     */
    public com.google.protobuf.ByteString
        getErrorMessageBytes() {
      java.lang.Object ref = errorMessage_;
      if (ref instanceof String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        errorMessage_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }
    /**
     * <pre>
     *错误消息文字内容。
     * </pre>
     *
     * <code>string errorMessage = 2;</code>
     * @param value The errorMessage to set.
     * @return This builder for chaining.
     */
    public Builder setErrorMessage(
        java.lang.String value) {
      if (value == null) {
    throw new NullPointerException();
  }
  
      errorMessage_ = value;
      onChanged();
      return this;
    }
    /**
     * <pre>
     *错误消息文字内容。
     * </pre>
     *
     * <code>string errorMessage = 2;</code>
     * @return This builder for chaining.
     */
    public Builder clearErrorMessage() {
      
      errorMessage_ = getDefaultInstance().getErrorMessage();
      onChanged();
      return this;
    }
    /**
     * <pre>
     *错误消息文字内容。
     * </pre>
     *
     * <code>string errorMessage = 2;</code>
     * @param value The bytes for errorMessage to set.
     * @return This builder for chaining.
     */
    public Builder setErrorMessageBytes(
        com.google.protobuf.ByteString value) {
      if (value == null) {
    throw new NullPointerException();
  }
  checkByteStringIsUtf8(value);
      
      errorMessage_ = value;
      onChanged();
      return this;
    }

    private java.lang.Object errorDetails_ = "";
    /**
     * <pre>
     *错误消息详情。
     * </pre>
     *
     * <code>string errorDetails = 3;</code>
     * @return The errorDetails.
     */
    public java.lang.String getErrorDetails() {
      java.lang.Object ref = errorDetails_;
      if (!(ref instanceof java.lang.String)) {
        com.google.protobuf.ByteString bs =
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        errorDetails_ = s;
        return s;
      } else {
        return (java.lang.String) ref;
      }
    }
    /**
     * <pre>
     *错误消息详情。
     * </pre>
     *
     * <code>string errorDetails = 3;</code>
     * @return The bytes for errorDetails.
     */
    public com.google.protobuf.ByteString
        getErrorDetailsBytes() {
      java.lang.Object ref = errorDetails_;
      if (ref instanceof String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        errorDetails_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }
    /**
     * <pre>
     *错误消息详情。
     * </pre>
     *
     * <code>string errorDetails = 3;</code>
     * @param value The errorDetails to set.
     * @return This builder for chaining.
     */
    public Builder setErrorDetails(
        java.lang.String value) {
      if (value == null) {
    throw new NullPointerException();
  }
  
      errorDetails_ = value;
      onChanged();
      return this;
    }
    /**
     * <pre>
     *错误消息详情。
     * </pre>
     *
     * <code>string errorDetails = 3;</code>
     * @return This builder for chaining.
     */
    public Builder clearErrorDetails() {
      
      errorDetails_ = getDefaultInstance().getErrorDetails();
      onChanged();
      return this;
    }
    /**
     * <pre>
     *错误消息详情。
     * </pre>
     *
     * <code>string errorDetails = 3;</code>
     * @param value The bytes for errorDetails to set.
     * @return This builder for chaining.
     */
    public Builder setErrorDetailsBytes(
        com.google.protobuf.ByteString value) {
      if (value == null) {
    throw new NullPointerException();
  }
  checkByteStringIsUtf8(value);
      
      errorDetails_ = value;
      onChanged();
      return this;
    }

    private java.lang.Object severityLevel_ = "";
    /**
     * <pre>
     *严重级别。
     * </pre>
     *
     * <code>string severityLevel = 4;</code>
     * @return The severityLevel.
     */
    public java.lang.String getSeverityLevel() {
      java.lang.Object ref = severityLevel_;
      if (!(ref instanceof java.lang.String)) {
        com.google.protobuf.ByteString bs =
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        severityLevel_ = s;
        return s;
      } else {
        return (java.lang.String) ref;
      }
    }
    /**
     * <pre>
     *严重级别。
     * </pre>
     *
     * <code>string severityLevel = 4;</code>
     * @return The bytes for severityLevel.
     */
    public com.google.protobuf.ByteString
        getSeverityLevelBytes() {
      java.lang.Object ref = severityLevel_;
      if (ref instanceof String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        severityLevel_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }
    /**
     * <pre>
     *严重级别。
     * </pre>
     *
     * <code>string severityLevel = 4;</code>
     * @param value The severityLevel to set.
     * @return This builder for chaining.
     */
    public Builder setSeverityLevel(
        java.lang.String value) {
      if (value == null) {
    throw new NullPointerException();
  }
  
      severityLevel_ = value;
      onChanged();
      return this;
    }
    /**
     * <pre>
     *严重级别。
     * </pre>
     *
     * <code>string severityLevel = 4;</code>
     * @return This builder for chaining.
     */
    public Builder clearSeverityLevel() {
      
      severityLevel_ = getDefaultInstance().getSeverityLevel();
      onChanged();
      return this;
    }
    /**
     * <pre>
     *严重级别。
     * </pre>
     *
     * <code>string severityLevel = 4;</code>
     * @param value The bytes for severityLevel to set.
     * @return This builder for chaining.
     */
    public Builder setSeverityLevelBytes(
        com.google.protobuf.ByteString value) {
      if (value == null) {
    throw new NullPointerException();
  }
  checkByteStringIsUtf8(value);
      
      severityLevel_ = value;
      onChanged();
      return this;
    }
    @java.lang.Override
    public final Builder setUnknownFields(
        final com.google.protobuf.UnknownFieldSet unknownFields) {
      return super.setUnknownFields(unknownFields);
    }

    @java.lang.Override
    public final Builder mergeUnknownFields(
        final com.google.protobuf.UnknownFieldSet unknownFields) {
      return super.mergeUnknownFields(unknownFields);
    }


    // @@protoc_insertion_point(builder_scope:com.stupidbeauty.hxlauncher.ReportErrorCodeReq)
  }

  // @@protoc_insertion_point(class_scope:com.stupidbeauty.hxlauncher.ReportErrorCodeReq)
  private static final com.stupidbeauty.hxlauncher.ReportErrorCodeReq DEFAULT_INSTANCE;
  static {
    DEFAULT_INSTANCE = new com.stupidbeauty.hxlauncher.ReportErrorCodeReq();
  }

  public static com.stupidbeauty.hxlauncher.ReportErrorCodeReq getDefaultInstance() {
    return DEFAULT_INSTANCE;
  }

  private static final com.google.protobuf.Parser<ReportErrorCodeReq>
      PARSER = new com.google.protobuf.AbstractParser<ReportErrorCodeReq>() {
    @java.lang.Override
    public ReportErrorCodeReq parsePartialFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return new ReportErrorCodeReq(input, extensionRegistry);
    }
  };

  public static com.google.protobuf.Parser<ReportErrorCodeReq> parser() {
    return PARSER;
  }

  @java.lang.Override
  public com.google.protobuf.Parser<ReportErrorCodeReq> getParserForType() {
    return PARSER;
  }

  @java.lang.Override
  public com.stupidbeauty.hxlauncher.ReportErrorCodeReq getDefaultInstanceForType() {
    return DEFAULT_INSTANCE;
  }

}

