// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: ReportFaceRecognizeResultReq.proto

package com.stupidbeauty.hxlauncher;

public final class ReportFaceRecognizeResultReqProtos {
  private ReportFaceRecognizeResultReqProtos() {}
  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistryLite registry) {
  }

  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistry registry) {
    registerAllExtensions(
        (com.google.protobuf.ExtensionRegistryLite) registry);
  }
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_com_stupidbeauty_hxlauncher_ReportFaceRecognizeResultReq_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_com_stupidbeauty_hxlauncher_ReportFaceRecognizeResultReq_fieldAccessorTable;

  public static com.google.protobuf.Descriptors.FileDescriptor
      getDescriptor() {
    return descriptor;
  }
  private static  com.google.protobuf.Descriptors.FileDescriptor
      descriptor;
  static {
    java.lang.String[] descriptorData = {
      "\n\"ReportFaceRecognizeResultReq.proto\022\033co" +
      "m.stupidbeauty.hxlauncher\"4\n\034ReportFaceR" +
      "ecognizeResultReq\022\024\n\014resultString\030\001 \001(\tB" +
      "C\n\033com.stupidbeauty.hxlauncherB\"ReportFa" +
      "ceRecognizeResultReqProtosP\001b\006proto3"
    };
    descriptor = com.google.protobuf.Descriptors.FileDescriptor
      .internalBuildGeneratedFileFrom(descriptorData,
        new com.google.protobuf.Descriptors.FileDescriptor[] {
        });
    internal_static_com_stupidbeauty_hxlauncher_ReportFaceRecognizeResultReq_descriptor =
      getDescriptor().getMessageTypes().get(0);
    internal_static_com_stupidbeauty_hxlauncher_ReportFaceRecognizeResultReq_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_com_stupidbeauty_hxlauncher_ReportFaceRecognizeResultReq_descriptor,
        new java.lang.String[] { "ResultString", });
  }

  // @@protoc_insertion_point(outer_class_scope)
}
