// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: ReportSpeechFinishedReq.proto

package com.stupidbeauty.hxlauncher;

public final class ReportSpeechFinishedReqProtos {
  private ReportSpeechFinishedReqProtos() {}
  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistryLite registry) {
  }

  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistry registry) {
    registerAllExtensions(
        (com.google.protobuf.ExtensionRegistryLite) registry);
  }
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_com_stupidbeauty_hxlauncher_ReportSpeechFinishedReq_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_com_stupidbeauty_hxlauncher_ReportSpeechFinishedReq_fieldAccessorTable;

  public static com.google.protobuf.Descriptors.FileDescriptor
      getDescriptor() {
    return descriptor;
  }
  private static  com.google.protobuf.Descriptors.FileDescriptor
      descriptor;
  static {
    java.lang.String[] descriptorData = {
      "\n\035ReportSpeechFinishedReq.proto\022\033com.stu" +
      "pidbeauty.hxlauncher\"5\n\027ReportSpeechFini" +
      "shedReq\022\032\n\022voiceTransactionId\030\001 \001(\tB>\n\033c" +
      "om.stupidbeauty.hxlauncherB\035ReportSpeech" +
      "FinishedReqProtosP\001b\006proto3"
    };
    com.google.protobuf.Descriptors.FileDescriptor.InternalDescriptorAssigner assigner =
        new com.google.protobuf.Descriptors.FileDescriptor.    InternalDescriptorAssigner() {
          public com.google.protobuf.ExtensionRegistry assignDescriptors(
              com.google.protobuf.Descriptors.FileDescriptor root) {
            descriptor = root;
            return null;
          }
        };
    com.google.protobuf.Descriptors.FileDescriptor
      .internalBuildGeneratedFileFrom(descriptorData,
        new com.google.protobuf.Descriptors.FileDescriptor[] {
        }, assigner);
    internal_static_com_stupidbeauty_hxlauncher_ReportSpeechFinishedReq_descriptor =
      getDescriptor().getMessageTypes().get(0);
    internal_static_com_stupidbeauty_hxlauncher_ReportSpeechFinishedReq_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_com_stupidbeauty_hxlauncher_ReportSpeechFinishedReq_descriptor,
        new java.lang.String[] { "VoiceTransactionId", });
  }

  // @@protoc_insertion_point(outer_class_scope)
}
