// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: ReportErrorCodeReq.proto

package com.stupidbeauty.hxlauncher;

public final class ReportErrorCodeReqProtos {
  private ReportErrorCodeReqProtos() {}
  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistryLite registry) {
  }

  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistry registry) {
    registerAllExtensions(
        (com.google.protobuf.ExtensionRegistryLite) registry);
  }
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_com_stupidbeauty_hxlauncher_ReportErrorCodeReq_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_com_stupidbeauty_hxlauncher_ReportErrorCodeReq_fieldAccessorTable;

  public static com.google.protobuf.Descriptors.FileDescriptor
      getDescriptor() {
    return descriptor;
  }
  private static  com.google.protobuf.Descriptors.FileDescriptor
      descriptor;
  static {
    java.lang.String[] descriptorData = {
      "\n\030ReportErrorCodeReq.proto\022\033com.stupidbe" +
      "auty.hxlauncher\"j\n\022ReportErrorCodeReq\022\021\n" +
      "\terrorCode\030\001 \001(\005\022\024\n\014errorMessage\030\002 \001(\t\022\024" +
      "\n\014errorDetails\030\003 \001(\t\022\025\n\rseverityLevel\030\004 " +
      "\001(\tB9\n\033com.stupidbeauty.hxlauncherB\030Repo" +
      "rtErrorCodeReqProtosP\001b\006proto3"
    };
    descriptor = com.google.protobuf.Descriptors.FileDescriptor
      .internalBuildGeneratedFileFrom(descriptorData,
        new com.google.protobuf.Descriptors.FileDescriptor[] {
        });
    internal_static_com_stupidbeauty_hxlauncher_ReportErrorCodeReq_descriptor =
      getDescriptor().getMessageTypes().get(0);
    internal_static_com_stupidbeauty_hxlauncher_ReportErrorCodeReq_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_com_stupidbeauty_hxlauncher_ReportErrorCodeReq_descriptor,
        new java.lang.String[] { "ErrorCode", "ErrorMessage", "ErrorDetails", "SeverityLevel", });
  }

  // @@protoc_insertion_point(outer_class_scope)
}
