// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: ReportMacroFinishedReq.proto

package com.stupidbeauty.hxlauncher;

public final class ReportMacroFinishedReqProtos {
  private ReportMacroFinishedReqProtos() {}
  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistryLite registry) {
  }

  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistry registry) {
    registerAllExtensions(
        (com.google.protobuf.ExtensionRegistryLite) registry);
  }
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_com_stupidbeauty_hxlauncher_ReportMacroFinishedReq_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_com_stupidbeauty_hxlauncher_ReportMacroFinishedReq_fieldAccessorTable;

  public static com.google.protobuf.Descriptors.FileDescriptor
      getDescriptor() {
    return descriptor;
  }
  private static  com.google.protobuf.Descriptors.FileDescriptor
      descriptor;
  static {
    java.lang.String[] descriptorData = {
      "\n\034ReportMacroFinishedReq.proto\022\033com.stup" +
      "idbeauty.hxlauncher\">\n\026ReportMacroFinish" +
      "edReq\022\017\n\007macroId\030\001 \001(\t\022\023\n\013macroResult\030\002 " +
      "\001(\tB=\n\033com.stupidbeauty.hxlauncherB\034Repo" +
      "rtMacroFinishedReqProtosP\001b\006proto3"
    };
    descriptor = com.google.protobuf.Descriptors.FileDescriptor
      .internalBuildGeneratedFileFrom(descriptorData,
        new com.google.protobuf.Descriptors.FileDescriptor[] {
        });
    internal_static_com_stupidbeauty_hxlauncher_ReportMacroFinishedReq_descriptor =
      getDescriptor().getMessageTypes().get(0);
    internal_static_com_stupidbeauty_hxlauncher_ReportMacroFinishedReq_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_com_stupidbeauty_hxlauncher_ReportMacroFinishedReq_descriptor,
        new java.lang.String[] { "MacroId", "MacroResult", });
  }

  // @@protoc_insertion_point(outer_class_scope)
}
