// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: ReportErrorCodeReq.proto

package com.stupidbeauty.hxlauncher;

public interface ReportErrorCodeReqOrBuilder extends
    // @@protoc_insertion_point(interface_extends:com.stupidbeauty.hxlauncher.ReportErrorCodeReq)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <pre>
   *错误码。
   * </pre>
   *
   * <code>int32 errorCode = 1;</code>
   * @return The errorCode.
   */
  int getErrorCode();

  /**
   * <pre>
   *错误消息文字内容。
   * </pre>
   *
   * <code>string errorMessage = 2;</code>
   * @return The errorMessage.
   */
  java.lang.String getErrorMessage();
  /**
   * <pre>
   *错误消息文字内容。
   * </pre>
   *
   * <code>string errorMessage = 2;</code>
   * @return The bytes for errorMessage.
   */
  com.google.protobuf.ByteString
      getErrorMessageBytes();

  /**
   * <pre>
   *错误消息详情。
   * </pre>
   *
   * <code>string errorDetails = 3;</code>
   * @return The errorDetails.
   */
  java.lang.String getErrorDetails();
  /**
   * <pre>
   *错误消息详情。
   * </pre>
   *
   * <code>string errorDetails = 3;</code>
   * @return The bytes for errorDetails.
   */
  com.google.protobuf.ByteString
      getErrorDetailsBytes();

  /**
   * <pre>
   *严重级别。
   * </pre>
   *
   * <code>string severityLevel = 4;</code>
   * @return The severityLevel.
   */
  java.lang.String getSeverityLevel();
  /**
   * <pre>
   *严重级别。
   * </pre>
   *
   * <code>string severityLevel = 4;</code>
   * @return The bytes for severityLevel.
   */
  com.google.protobuf.ByteString
      getSeverityLevelBytes();
}
