// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: ReportSpeechFinishedReq.proto

package com.stupidbeauty.hxlauncher;

public interface ReportSpeechFinishedReqOrBuilder extends
    // @@protoc_insertion_point(interface_extends:com.stupidbeauty.hxlauncher.ReportSpeechFinishedReq)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <pre>
   *语音发声事务编号。
   * </pre>
   *
   * <code>string voiceTransactionId = 1;</code>
   */
  java.lang.String getVoiceTransactionId();
  /**
   * <pre>
   *语音发声事务编号。
   * </pre>
   *
   * <code>string voiceTransactionId = 1;</code>
   */
  com.google.protobuf.ByteString
      getVoiceTransactionIdBytes();
}
