// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: ReportMacroFinishedReq.proto

package com.stupidbeauty.hxlauncher;

public interface ReportMacroFinishedReqOrBuilder extends
    // @@protoc_insertion_point(interface_extends:com.stupidbeauty.hxlauncher.ReportMacroFinishedReq)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <pre>
   *宏编号。
   * </pre>
   *
   * <code>string macroId = 1;</code>
   * @return The macroId.
   */
  java.lang.String getMacroId();
  /**
   * <pre>
   *宏编号。
   * </pre>
   *
   * <code>string macroId = 1;</code>
   * @return The bytes for macroId.
   */
  com.google.protobuf.ByteString
      getMacroIdBytes();

  /**
   * <pre>
   *宏执行结果。
   * </pre>
   *
   * <code>string macroResult = 2;</code>
   * @return The macroResult.
   */
  java.lang.String getMacroResult();
  /**
   * <pre>
   *宏执行结果。
   * </pre>
   *
   * <code>string macroResult = 2;</code>
   * @return The bytes for macroResult.
   */
  com.google.protobuf.ByteString
      getMacroResultBytes();
}
