// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: ReportMacroFinishedReq.proto

package com.stupidbeauty.hxlauncher;

/**
 * Protobuf type {@code com.stupidbeauty.hxlauncher.ReportMacroFinishedReq}
 */
public  final class ReportMacroFinishedReq extends
    com.google.protobuf.GeneratedMessageV3 implements
    // @@protoc_insertion_point(message_implements:com.stupidbeauty.hxlauncher.ReportMacroFinishedReq)
    ReportMacroFinishedReqOrBuilder {
private static final long serialVersionUID = 0L;
  // Use ReportMacroFinishedReq.newBuilder() to construct.
  private ReportMacroFinishedReq(com.google.protobuf.GeneratedMessageV3.Builder<?> builder) {
    super(builder);
  }
  private ReportMacroFinishedReq() {
    macroId_ = "";
    macroResult_ = "";
  }

  @java.lang.Override
  @SuppressWarnings({"unused"})
  protected java.lang.Object newInstance(
      UnusedPrivateParameter unused) {
    return new ReportMacroFinishedReq();
  }

  @java.lang.Override
  public final com.google.protobuf.UnknownFieldSet
  getUnknownFields() {
    return this.unknownFields;
  }
  private ReportMacroFinishedReq(
      com.google.protobuf.CodedInputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    this();
    if (extensionRegistry == null) {
      throw new java.lang.NullPointerException();
    }
    com.google.protobuf.UnknownFieldSet.Builder unknownFields =
        com.google.protobuf.UnknownFieldSet.newBuilder();
    try {
      boolean done = false;
      while (!done) {
        int tag = input.readTag();
        switch (tag) {
          case 0:
            done = true;
            break;
          case 10: {
            java.lang.String s = input.readStringRequireUtf8();

            macroId_ = s;
            break;
          }
          case 18: {
            java.lang.String s = input.readStringRequireUtf8();

            macroResult_ = s;
            break;
          }
          default: {
            if (!parseUnknownField(
                input, unknownFields, extensionRegistry, tag)) {
              done = true;
            }
            break;
          }
        }
      }
    } catch (com.google.protobuf.InvalidProtocolBufferException e) {
      throw e.setUnfinishedMessage(this);
    } catch (java.io.IOException e) {
      throw new com.google.protobuf.InvalidProtocolBufferException(
          e).setUnfinishedMessage(this);
    } finally {
      this.unknownFields = unknownFields.build();
      makeExtensionsImmutable();
    }
  }
  public static final com.google.protobuf.Descriptors.Descriptor
      getDescriptor() {
    return com.stupidbeauty.hxlauncher.ReportMacroFinishedReqProtos.internal_static_com_stupidbeauty_hxlauncher_ReportMacroFinishedReq_descriptor;
  }

  @java.lang.Override
  protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internalGetFieldAccessorTable() {
    return com.stupidbeauty.hxlauncher.ReportMacroFinishedReqProtos.internal_static_com_stupidbeauty_hxlauncher_ReportMacroFinishedReq_fieldAccessorTable
        .ensureFieldAccessorsInitialized(
            com.stupidbeauty.hxlauncher.ReportMacroFinishedReq.class, com.stupidbeauty.hxlauncher.ReportMacroFinishedReq.Builder.class);
  }

  public static final int MACROID_FIELD_NUMBER = 1;
  private volatile java.lang.Object macroId_;
  /**
   * <pre>
   *宏编号。
   * </pre>
   *
   * <code>string macroId = 1;</code>
   * @return The macroId.
   */
  public java.lang.String getMacroId() {
    java.lang.Object ref = macroId_;
    if (ref instanceof java.lang.String) {
      return (java.lang.String) ref;
    } else {
      com.google.protobuf.ByteString bs = 
          (com.google.protobuf.ByteString) ref;
      java.lang.String s = bs.toStringUtf8();
      macroId_ = s;
      return s;
    }
  }
  /**
   * <pre>
   *宏编号。
   * </pre>
   *
   * <code>string macroId = 1;</code>
   * @return The bytes for macroId.
   */
  public com.google.protobuf.ByteString
      getMacroIdBytes() {
    java.lang.Object ref = macroId_;
    if (ref instanceof java.lang.String) {
      com.google.protobuf.ByteString b = 
          com.google.protobuf.ByteString.copyFromUtf8(
              (java.lang.String) ref);
      macroId_ = b;
      return b;
    } else {
      return (com.google.protobuf.ByteString) ref;
    }
  }

  public static final int MACRORESULT_FIELD_NUMBER = 2;
  private volatile java.lang.Object macroResult_;
  /**
   * <pre>
   *宏执行结果。
   * </pre>
   *
   * <code>string macroResult = 2;</code>
   * @return The macroResult.
   */
  public java.lang.String getMacroResult() {
    java.lang.Object ref = macroResult_;
    if (ref instanceof java.lang.String) {
      return (java.lang.String) ref;
    } else {
      com.google.protobuf.ByteString bs = 
          (com.google.protobuf.ByteString) ref;
      java.lang.String s = bs.toStringUtf8();
      macroResult_ = s;
      return s;
    }
  }
  /**
   * <pre>
   *宏执行结果。
   * </pre>
   *
   * <code>string macroResult = 2;</code>
   * @return The bytes for macroResult.
   */
  public com.google.protobuf.ByteString
      getMacroResultBytes() {
    java.lang.Object ref = macroResult_;
    if (ref instanceof java.lang.String) {
      com.google.protobuf.ByteString b = 
          com.google.protobuf.ByteString.copyFromUtf8(
              (java.lang.String) ref);
      macroResult_ = b;
      return b;
    } else {
      return (com.google.protobuf.ByteString) ref;
    }
  }

  private byte memoizedIsInitialized = -1;
  @java.lang.Override
  public final boolean isInitialized() {
    byte isInitialized = memoizedIsInitialized;
    if (isInitialized == 1) return true;
    if (isInitialized == 0) return false;

    memoizedIsInitialized = 1;
    return true;
  }

  @java.lang.Override
  public void writeTo(com.google.protobuf.CodedOutputStream output)
                      throws java.io.IOException {
    if (!getMacroIdBytes().isEmpty()) {
      com.google.protobuf.GeneratedMessageV3.writeString(output, 1, macroId_);
    }
    if (!getMacroResultBytes().isEmpty()) {
      com.google.protobuf.GeneratedMessageV3.writeString(output, 2, macroResult_);
    }
    unknownFields.writeTo(output);
  }

  @java.lang.Override
  public int getSerializedSize() {
    int size = memoizedSize;
    if (size != -1) return size;

    size = 0;
    if (!getMacroIdBytes().isEmpty()) {
      size += com.google.protobuf.GeneratedMessageV3.computeStringSize(1, macroId_);
    }
    if (!getMacroResultBytes().isEmpty()) {
      size += com.google.protobuf.GeneratedMessageV3.computeStringSize(2, macroResult_);
    }
    size += unknownFields.getSerializedSize();
    memoizedSize = size;
    return size;
  }

  @java.lang.Override
  public boolean equals(final java.lang.Object obj) {
    if (obj == this) {
     return true;
    }
    if (!(obj instanceof com.stupidbeauty.hxlauncher.ReportMacroFinishedReq)) {
      return super.equals(obj);
    }
    com.stupidbeauty.hxlauncher.ReportMacroFinishedReq other = (com.stupidbeauty.hxlauncher.ReportMacroFinishedReq) obj;

    if (!getMacroId()
        .equals(other.getMacroId())) return false;
    if (!getMacroResult()
        .equals(other.getMacroResult())) return false;
    if (!unknownFields.equals(other.unknownFields)) return false;
    return true;
  }

  @java.lang.Override
  public int hashCode() {
    if (memoizedHashCode != 0) {
      return memoizedHashCode;
    }
    int hash = 41;
    hash = (19 * hash) + getDescriptor().hashCode();
    hash = (37 * hash) + MACROID_FIELD_NUMBER;
    hash = (53 * hash) + getMacroId().hashCode();
    hash = (37 * hash) + MACRORESULT_FIELD_NUMBER;
    hash = (53 * hash) + getMacroResult().hashCode();
    hash = (29 * hash) + unknownFields.hashCode();
    memoizedHashCode = hash;
    return hash;
  }

  public static com.stupidbeauty.hxlauncher.ReportMacroFinishedReq parseFrom(
      java.nio.ByteBuffer data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static com.stupidbeauty.hxlauncher.ReportMacroFinishedReq parseFrom(
      java.nio.ByteBuffer data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static com.stupidbeauty.hxlauncher.ReportMacroFinishedReq parseFrom(
      com.google.protobuf.ByteString data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static com.stupidbeauty.hxlauncher.ReportMacroFinishedReq parseFrom(
      com.google.protobuf.ByteString data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static com.stupidbeauty.hxlauncher.ReportMacroFinishedReq parseFrom(byte[] data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static com.stupidbeauty.hxlauncher.ReportMacroFinishedReq parseFrom(
      byte[] data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static com.stupidbeauty.hxlauncher.ReportMacroFinishedReq parseFrom(java.io.InputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input);
  }
  public static com.stupidbeauty.hxlauncher.ReportMacroFinishedReq parseFrom(
      java.io.InputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input, extensionRegistry);
  }
  public static com.stupidbeauty.hxlauncher.ReportMacroFinishedReq parseDelimitedFrom(java.io.InputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseDelimitedWithIOException(PARSER, input);
  }
  public static com.stupidbeauty.hxlauncher.ReportMacroFinishedReq parseDelimitedFrom(
      java.io.InputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseDelimitedWithIOException(PARSER, input, extensionRegistry);
  }
  public static com.stupidbeauty.hxlauncher.ReportMacroFinishedReq parseFrom(
      com.google.protobuf.CodedInputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input);
  }
  public static com.stupidbeauty.hxlauncher.ReportMacroFinishedReq parseFrom(
      com.google.protobuf.CodedInputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input, extensionRegistry);
  }

  @java.lang.Override
  public Builder newBuilderForType() { return newBuilder(); }
  public static Builder newBuilder() {
    return DEFAULT_INSTANCE.toBuilder();
  }
  public static Builder newBuilder(com.stupidbeauty.hxlauncher.ReportMacroFinishedReq prototype) {
    return DEFAULT_INSTANCE.toBuilder().mergeFrom(prototype);
  }
  @java.lang.Override
  public Builder toBuilder() {
    return this == DEFAULT_INSTANCE
        ? new Builder() : new Builder().mergeFrom(this);
  }

  @java.lang.Override
  protected Builder newBuilderForType(
      com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
    Builder builder = new Builder(parent);
    return builder;
  }
  /**
   * Protobuf type {@code com.stupidbeauty.hxlauncher.ReportMacroFinishedReq}
   */
  public static final class Builder extends
      com.google.protobuf.GeneratedMessageV3.Builder<Builder> implements
      // @@protoc_insertion_point(builder_implements:com.stupidbeauty.hxlauncher.ReportMacroFinishedReq)
      com.stupidbeauty.hxlauncher.ReportMacroFinishedReqOrBuilder {
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return com.stupidbeauty.hxlauncher.ReportMacroFinishedReqProtos.internal_static_com_stupidbeauty_hxlauncher_ReportMacroFinishedReq_descriptor;
    }

    @java.lang.Override
    protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return com.stupidbeauty.hxlauncher.ReportMacroFinishedReqProtos.internal_static_com_stupidbeauty_hxlauncher_ReportMacroFinishedReq_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              com.stupidbeauty.hxlauncher.ReportMacroFinishedReq.class, com.stupidbeauty.hxlauncher.ReportMacroFinishedReq.Builder.class);
    }

    // Construct using com.stupidbeauty.hxlauncher.ReportMacroFinishedReq.newBuilder()
    private Builder() {
      maybeForceBuilderInitialization();
    }

    private Builder(
        com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
      super(parent);
      maybeForceBuilderInitialization();
    }
    private void maybeForceBuilderInitialization() {
      if (com.google.protobuf.GeneratedMessageV3
              .alwaysUseFieldBuilders) {
      }
    }
    @java.lang.Override
    public Builder clear() {
      super.clear();
      macroId_ = "";

      macroResult_ = "";

      return this;
    }

    @java.lang.Override
    public com.google.protobuf.Descriptors.Descriptor
        getDescriptorForType() {
      return com.stupidbeauty.hxlauncher.ReportMacroFinishedReqProtos.internal_static_com_stupidbeauty_hxlauncher_ReportMacroFinishedReq_descriptor;
    }

    @java.lang.Override
    public com.stupidbeauty.hxlauncher.ReportMacroFinishedReq getDefaultInstanceForType() {
      return com.stupidbeauty.hxlauncher.ReportMacroFinishedReq.getDefaultInstance();
    }

    @java.lang.Override
    public com.stupidbeauty.hxlauncher.ReportMacroFinishedReq build() {
      com.stupidbeauty.hxlauncher.ReportMacroFinishedReq result = buildPartial();
      if (!result.isInitialized()) {
        throw newUninitializedMessageException(result);
      }
      return result;
    }

    @java.lang.Override
    public com.stupidbeauty.hxlauncher.ReportMacroFinishedReq buildPartial() {
      com.stupidbeauty.hxlauncher.ReportMacroFinishedReq result = new com.stupidbeauty.hxlauncher.ReportMacroFinishedReq(this);
      result.macroId_ = macroId_;
      result.macroResult_ = macroResult_;
      onBuilt();
      return result;
    }

    @java.lang.Override
    public Builder clone() {
      return super.clone();
    }
    @java.lang.Override
    public Builder setField(
        com.google.protobuf.Descriptors.FieldDescriptor field,
        java.lang.Object value) {
      return super.setField(field, value);
    }
    @java.lang.Override
    public Builder clearField(
        com.google.protobuf.Descriptors.FieldDescriptor field) {
      return super.clearField(field);
    }
    @java.lang.Override
    public Builder clearOneof(
        com.google.protobuf.Descriptors.OneofDescriptor oneof) {
      return super.clearOneof(oneof);
    }
    @java.lang.Override
    public Builder setRepeatedField(
        com.google.protobuf.Descriptors.FieldDescriptor field,
        int index, java.lang.Object value) {
      return super.setRepeatedField(field, index, value);
    }
    @java.lang.Override
    public Builder addRepeatedField(
        com.google.protobuf.Descriptors.FieldDescriptor field,
        java.lang.Object value) {
      return super.addRepeatedField(field, value);
    }
    @java.lang.Override
    public Builder mergeFrom(com.google.protobuf.Message other) {
      if (other instanceof com.stupidbeauty.hxlauncher.ReportMacroFinishedReq) {
        return mergeFrom((com.stupidbeauty.hxlauncher.ReportMacroFinishedReq)other);
      } else {
        super.mergeFrom(other);
        return this;
      }
    }

    public Builder mergeFrom(com.stupidbeauty.hxlauncher.ReportMacroFinishedReq other) {
      if (other == com.stupidbeauty.hxlauncher.ReportMacroFinishedReq.getDefaultInstance()) return this;
      if (!other.getMacroId().isEmpty()) {
        macroId_ = other.macroId_;
        onChanged();
      }
      if (!other.getMacroResult().isEmpty()) {
        macroResult_ = other.macroResult_;
        onChanged();
      }
      this.mergeUnknownFields(other.unknownFields);
      onChanged();
      return this;
    }

    @java.lang.Override
    public final boolean isInitialized() {
      return true;
    }

    @java.lang.Override
    public Builder mergeFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      com.stupidbeauty.hxlauncher.ReportMacroFinishedReq parsedMessage = null;
      try {
        parsedMessage = PARSER.parsePartialFrom(input, extensionRegistry);
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        parsedMessage = (com.stupidbeauty.hxlauncher.ReportMacroFinishedReq) e.getUnfinishedMessage();
        throw e.unwrapIOException();
      } finally {
        if (parsedMessage != null) {
          mergeFrom(parsedMessage);
        }
      }
      return this;
    }

    private java.lang.Object macroId_ = "";
    /**
     * <pre>
     *宏编号。
     * </pre>
     *
     * <code>string macroId = 1;</code>
     * @return The macroId.
     */
    public java.lang.String getMacroId() {
      java.lang.Object ref = macroId_;
      if (!(ref instanceof java.lang.String)) {
        com.google.protobuf.ByteString bs =
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        macroId_ = s;
        return s;
      } else {
        return (java.lang.String) ref;
      }
    }
    /**
     * <pre>
     *宏编号。
     * </pre>
     *
     * <code>string macroId = 1;</code>
     * @return The bytes for macroId.
     */
    public com.google.protobuf.ByteString
        getMacroIdBytes() {
      java.lang.Object ref = macroId_;
      if (ref instanceof String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        macroId_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }
    /**
     * <pre>
     *宏编号。
     * </pre>
     *
     * <code>string macroId = 1;</code>
     * @param value The macroId to set.
     * @return This builder for chaining.
     */
    public Builder setMacroId(
        java.lang.String value) {
      if (value == null) {
    throw new NullPointerException();
  }
  
      macroId_ = value;
      onChanged();
      return this;
    }
    /**
     * <pre>
     *宏编号。
     * </pre>
     *
     * <code>string macroId = 1;</code>
     * @return This builder for chaining.
     */
    public Builder clearMacroId() {
      
      macroId_ = getDefaultInstance().getMacroId();
      onChanged();
      return this;
    }
    /**
     * <pre>
     *宏编号。
     * </pre>
     *
     * <code>string macroId = 1;</code>
     * @param value The bytes for macroId to set.
     * @return This builder for chaining.
     */
    public Builder setMacroIdBytes(
        com.google.protobuf.ByteString value) {
      if (value == null) {
    throw new NullPointerException();
  }
  checkByteStringIsUtf8(value);
      
      macroId_ = value;
      onChanged();
      return this;
    }

    private java.lang.Object macroResult_ = "";
    /**
     * <pre>
     *宏执行结果。
     * </pre>
     *
     * <code>string macroResult = 2;</code>
     * @return The macroResult.
     */
    public java.lang.String getMacroResult() {
      java.lang.Object ref = macroResult_;
      if (!(ref instanceof java.lang.String)) {
        com.google.protobuf.ByteString bs =
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        macroResult_ = s;
        return s;
      } else {
        return (java.lang.String) ref;
      }
    }
    /**
     * <pre>
     *宏执行结果。
     * </pre>
     *
     * <code>string macroResult = 2;</code>
     * @return The bytes for macroResult.
     */
    public com.google.protobuf.ByteString
        getMacroResultBytes() {
      java.lang.Object ref = macroResult_;
      if (ref instanceof String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        macroResult_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }
    /**
     * <pre>
     *宏执行结果。
     * </pre>
     *
     * <code>string macroResult = 2;</code>
     * @param value The macroResult to set.
     * @return This builder for chaining.
     */
    public Builder setMacroResult(
        java.lang.String value) {
      if (value == null) {
    throw new NullPointerException();
  }
  
      macroResult_ = value;
      onChanged();
      return this;
    }
    /**
     * <pre>
     *宏执行结果。
     * </pre>
     *
     * <code>string macroResult = 2;</code>
     * @return This builder for chaining.
     */
    public Builder clearMacroResult() {
      
      macroResult_ = getDefaultInstance().getMacroResult();
      onChanged();
      return this;
    }
    /**
     * <pre>
     *宏执行结果。
     * </pre>
     *
     * <code>string macroResult = 2;</code>
     * @param value The bytes for macroResult to set.
     * @return This builder for chaining.
     */
    public Builder setMacroResultBytes(
        com.google.protobuf.ByteString value) {
      if (value == null) {
    throw new NullPointerException();
  }
  checkByteStringIsUtf8(value);
      
      macroResult_ = value;
      onChanged();
      return this;
    }
    @java.lang.Override
    public final Builder setUnknownFields(
        final com.google.protobuf.UnknownFieldSet unknownFields) {
      return super.setUnknownFields(unknownFields);
    }

    @java.lang.Override
    public final Builder mergeUnknownFields(
        final com.google.protobuf.UnknownFieldSet unknownFields) {
      return super.mergeUnknownFields(unknownFields);
    }


    // @@protoc_insertion_point(builder_scope:com.stupidbeauty.hxlauncher.ReportMacroFinishedReq)
  }

  // @@protoc_insertion_point(class_scope:com.stupidbeauty.hxlauncher.ReportMacroFinishedReq)
  private static final com.stupidbeauty.hxlauncher.ReportMacroFinishedReq DEFAULT_INSTANCE;
  static {
    DEFAULT_INSTANCE = new com.stupidbeauty.hxlauncher.ReportMacroFinishedReq();
  }

  public static com.stupidbeauty.hxlauncher.ReportMacroFinishedReq getDefaultInstance() {
    return DEFAULT_INSTANCE;
  }

  private static final com.google.protobuf.Parser<ReportMacroFinishedReq>
      PARSER = new com.google.protobuf.AbstractParser<ReportMacroFinishedReq>() {
    @java.lang.Override
    public ReportMacroFinishedReq parsePartialFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return new ReportMacroFinishedReq(input, extensionRegistry);
    }
  };

  public static com.google.protobuf.Parser<ReportMacroFinishedReq> parser() {
    return PARSER;
  }

  @java.lang.Override
  public com.google.protobuf.Parser<ReportMacroFinishedReq> getParserForType() {
    return PARSER;
  }

  @java.lang.Override
  public com.stupidbeauty.hxlauncher.ReportMacroFinishedReq getDefaultInstanceForType() {
    return DEFAULT_INSTANCE;
  }

}

