// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: ShowErrorCodePageReq.proto

package com.stupidbeauty.hxlauncher;

public interface ShowErrorCodePageReqOrBuilder extends
    // @@protoc_insertion_point(interface_extends:com.stupidbeauty.hxlauncher.ShowErrorCodePageReq)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <pre>
   *错误码。
   * </pre>
   *
   * <code>int32 errorCode = 1;</code>
   * @return The errorCode.
   */
  int getErrorCode();

  /**
   * <pre>
   *错误消息文字内容。
   * </pre>
   *
   * <code>string errorMessage = 2;</code>
   * @return The errorMessage.
   */
  java.lang.String getErrorMessage();
  /**
   * <pre>
   *错误消息文字内容。
   * </pre>
   *
   * <code>string errorMessage = 2;</code>
   * @return The bytes for errorMessage.
   */
  com.google.protobuf.ByteString
      getErrorMessageBytes();
}
