// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: ShowErrorCodePageReq.proto

package com.stupidbeauty.hxlauncher;

public final class ShowErrorCodePageReqProtos {
  private ShowErrorCodePageReqProtos() {}
  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistryLite registry) {
  }

  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistry registry) {
    registerAllExtensions(
        (com.google.protobuf.ExtensionRegistryLite) registry);
  }
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_com_stupidbeauty_hxlauncher_ShowErrorCodePageReq_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_com_stupidbeauty_hxlauncher_ShowErrorCodePageReq_fieldAccessorTable;

  public static com.google.protobuf.Descriptors.FileDescriptor
      getDescriptor() {
    return descriptor;
  }
  private static  com.google.protobuf.Descriptors.FileDescriptor
      descriptor;
  static {
    java.lang.String[] descriptorData = {
      "\n\032ShowErrorCodePageReq.proto\022\033com.stupid" +
      "beauty.hxlauncher\"?\n\024ShowErrorCodePageRe" +
      "q\022\021\n\terrorCode\030\001 \001(\005\022\024\n\014errorMessage\030\002 \001" +
      "(\tB;\n\033com.stupidbeauty.hxlauncherB\032ShowE" +
      "rrorCodePageReqProtosP\001b\006proto3"
    };
    descriptor = com.google.protobuf.Descriptors.FileDescriptor
      .internalBuildGeneratedFileFrom(descriptorData,
        new com.google.protobuf.Descriptors.FileDescriptor[] {
        });
    internal_static_com_stupidbeauty_hxlauncher_ShowErrorCodePageReq_descriptor =
      getDescriptor().getMessageTypes().get(0);
    internal_static_com_stupidbeauty_hxlauncher_ShowErrorCodePageReq_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_com_stupidbeauty_hxlauncher_ShowErrorCodePageReq_descriptor,
        new java.lang.String[] { "ErrorCode", "ErrorMessage", });
  }

  // @@protoc_insertion_point(outer_class_scope)
}
