// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: StartFaceRecognizeReq.proto

package com.stupidbeauty.hxlauncher;

/**
 * Protobuf type {@code com.stupidbeauty.hxlauncher.StartFaceRecognizeReq}
 */
public  final class StartFaceRecognizeReq extends
    com.google.protobuf.GeneratedMessageV3 implements
    // @@protoc_insertion_point(message_implements:com.stupidbeauty.hxlauncher.StartFaceRecognizeReq)
    StartFaceRecognizeReqOrBuilder {
private static final long serialVersionUID = 0L;
  // Use StartFaceRecognizeReq.newBuilder() to construct.
  private StartFaceRecognizeReq(com.google.protobuf.GeneratedMessageV3.Builder<?> builder) {
    super(builder);
  }
  private StartFaceRecognizeReq() {
    maxFaceAmount_ = 0;
    detectMaxFaceAmount_ = 0;
  }

  @java.lang.Override
  public final com.google.protobuf.UnknownFieldSet
  getUnknownFields() {
    return this.unknownFields;
  }
  private StartFaceRecognizeReq(
      com.google.protobuf.CodedInputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    this();
    if (extensionRegistry == null) {
      throw new java.lang.NullPointerException();
    }
    int mutable_bitField0_ = 0;
    com.google.protobuf.UnknownFieldSet.Builder unknownFields =
        com.google.protobuf.UnknownFieldSet.newBuilder();
    try {
      boolean done = false;
      while (!done) {
        int tag = input.readTag();
        switch (tag) {
          case 0:
            done = true;
            break;
          case 8: {

            maxFaceAmount_ = input.readInt32();
            break;
          }
          case 16: {

            detectMaxFaceAmount_ = input.readInt32();
            break;
          }
          default: {
            if (!parseUnknownFieldProto3(
                input, unknownFields, extensionRegistry, tag)) {
              done = true;
            }
            break;
          }
        }
      }
    } catch (com.google.protobuf.InvalidProtocolBufferException e) {
      throw e.setUnfinishedMessage(this);
    } catch (java.io.IOException e) {
      throw new com.google.protobuf.InvalidProtocolBufferException(
          e).setUnfinishedMessage(this);
    } finally {
      this.unknownFields = unknownFields.build();
      makeExtensionsImmutable();
    }
  }
  public static final com.google.protobuf.Descriptors.Descriptor
      getDescriptor() {
    return com.stupidbeauty.hxlauncher.StartFaceRecognizeReqProtos.internal_static_com_stupidbeauty_hxlauncher_StartFaceRecognizeReq_descriptor;
  }

  @java.lang.Override
  protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internalGetFieldAccessorTable() {
    return com.stupidbeauty.hxlauncher.StartFaceRecognizeReqProtos.internal_static_com_stupidbeauty_hxlauncher_StartFaceRecognizeReq_fieldAccessorTable
        .ensureFieldAccessorsInitialized(
            com.stupidbeauty.hxlauncher.StartFaceRecognizeReq.class, com.stupidbeauty.hxlauncher.StartFaceRecognizeReq.Builder.class);
  }

  public static final int MAXFACEAMOUNT_FIELD_NUMBER = 1;
  private int maxFaceAmount_;
  /**
   * <pre>
   *最多的人脸个数。
   * </pre>
   *
   * <code>int32 maxFaceAmount = 1;</code>
   */
  public int getMaxFaceAmount() {
    return maxFaceAmount_;
  }

  public static final int DETECTMAXFACEAMOUNT_FIELD_NUMBER = 2;
  private int detectMaxFaceAmount_;
  /**
   * <pre>
   *最多允许检测到以进行识别的人脸个数。
   * </pre>
   *
   * <code>int32 detectMaxFaceAmount = 2;</code>
   */
  public int getDetectMaxFaceAmount() {
    return detectMaxFaceAmount_;
  }

  private byte memoizedIsInitialized = -1;
  @java.lang.Override
  public final boolean isInitialized() {
    byte isInitialized = memoizedIsInitialized;
    if (isInitialized == 1) return true;
    if (isInitialized == 0) return false;

    memoizedIsInitialized = 1;
    return true;
  }

  @java.lang.Override
  public void writeTo(com.google.protobuf.CodedOutputStream output)
                      throws java.io.IOException {
    if (maxFaceAmount_ != 0) {
      output.writeInt32(1, maxFaceAmount_);
    }
    if (detectMaxFaceAmount_ != 0) {
      output.writeInt32(2, detectMaxFaceAmount_);
    }
    unknownFields.writeTo(output);
  }

  @java.lang.Override
  public int getSerializedSize() {
    int size = memoizedSize;
    if (size != -1) return size;

    size = 0;
    if (maxFaceAmount_ != 0) {
      size += com.google.protobuf.CodedOutputStream
        .computeInt32Size(1, maxFaceAmount_);
    }
    if (detectMaxFaceAmount_ != 0) {
      size += com.google.protobuf.CodedOutputStream
        .computeInt32Size(2, detectMaxFaceAmount_);
    }
    size += unknownFields.getSerializedSize();
    memoizedSize = size;
    return size;
  }

  @java.lang.Override
  public boolean equals(final java.lang.Object obj) {
    if (obj == this) {
     return true;
    }
    if (!(obj instanceof com.stupidbeauty.hxlauncher.StartFaceRecognizeReq)) {
      return super.equals(obj);
    }
    com.stupidbeauty.hxlauncher.StartFaceRecognizeReq other = (com.stupidbeauty.hxlauncher.StartFaceRecognizeReq) obj;

    boolean result = true;
    result = result && (getMaxFaceAmount()
        == other.getMaxFaceAmount());
    result = result && (getDetectMaxFaceAmount()
        == other.getDetectMaxFaceAmount());
    result = result && unknownFields.equals(other.unknownFields);
    return result;
  }

  @java.lang.Override
  public int hashCode() {
    if (memoizedHashCode != 0) {
      return memoizedHashCode;
    }
    int hash = 41;
    hash = (19 * hash) + getDescriptor().hashCode();
    hash = (37 * hash) + MAXFACEAMOUNT_FIELD_NUMBER;
    hash = (53 * hash) + getMaxFaceAmount();
    hash = (37 * hash) + DETECTMAXFACEAMOUNT_FIELD_NUMBER;
    hash = (53 * hash) + getDetectMaxFaceAmount();
    hash = (29 * hash) + unknownFields.hashCode();
    memoizedHashCode = hash;
    return hash;
  }

  public static com.stupidbeauty.hxlauncher.StartFaceRecognizeReq parseFrom(
      java.nio.ByteBuffer data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static com.stupidbeauty.hxlauncher.StartFaceRecognizeReq parseFrom(
      java.nio.ByteBuffer data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static com.stupidbeauty.hxlauncher.StartFaceRecognizeReq parseFrom(
      com.google.protobuf.ByteString data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static com.stupidbeauty.hxlauncher.StartFaceRecognizeReq parseFrom(
      com.google.protobuf.ByteString data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static com.stupidbeauty.hxlauncher.StartFaceRecognizeReq parseFrom(byte[] data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static com.stupidbeauty.hxlauncher.StartFaceRecognizeReq parseFrom(
      byte[] data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static com.stupidbeauty.hxlauncher.StartFaceRecognizeReq parseFrom(java.io.InputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input);
  }
  public static com.stupidbeauty.hxlauncher.StartFaceRecognizeReq parseFrom(
      java.io.InputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input, extensionRegistry);
  }
  public static com.stupidbeauty.hxlauncher.StartFaceRecognizeReq parseDelimitedFrom(java.io.InputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseDelimitedWithIOException(PARSER, input);
  }
  public static com.stupidbeauty.hxlauncher.StartFaceRecognizeReq parseDelimitedFrom(
      java.io.InputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseDelimitedWithIOException(PARSER, input, extensionRegistry);
  }
  public static com.stupidbeauty.hxlauncher.StartFaceRecognizeReq parseFrom(
      com.google.protobuf.CodedInputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input);
  }
  public static com.stupidbeauty.hxlauncher.StartFaceRecognizeReq parseFrom(
      com.google.protobuf.CodedInputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input, extensionRegistry);
  }

  @java.lang.Override
  public Builder newBuilderForType() { return newBuilder(); }
  public static Builder newBuilder() {
    return DEFAULT_INSTANCE.toBuilder();
  }
  public static Builder newBuilder(com.stupidbeauty.hxlauncher.StartFaceRecognizeReq prototype) {
    return DEFAULT_INSTANCE.toBuilder().mergeFrom(prototype);
  }
  @java.lang.Override
  public Builder toBuilder() {
    return this == DEFAULT_INSTANCE
        ? new Builder() : new Builder().mergeFrom(this);
  }

  @java.lang.Override
  protected Builder newBuilderForType(
      com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
    Builder builder = new Builder(parent);
    return builder;
  }
  /**
   * Protobuf type {@code com.stupidbeauty.hxlauncher.StartFaceRecognizeReq}
   */
  public static final class Builder extends
      com.google.protobuf.GeneratedMessageV3.Builder<Builder> implements
      // @@protoc_insertion_point(builder_implements:com.stupidbeauty.hxlauncher.StartFaceRecognizeReq)
      com.stupidbeauty.hxlauncher.StartFaceRecognizeReqOrBuilder {
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return com.stupidbeauty.hxlauncher.StartFaceRecognizeReqProtos.internal_static_com_stupidbeauty_hxlauncher_StartFaceRecognizeReq_descriptor;
    }

    @java.lang.Override
    protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return com.stupidbeauty.hxlauncher.StartFaceRecognizeReqProtos.internal_static_com_stupidbeauty_hxlauncher_StartFaceRecognizeReq_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              com.stupidbeauty.hxlauncher.StartFaceRecognizeReq.class, com.stupidbeauty.hxlauncher.StartFaceRecognizeReq.Builder.class);
    }

    // Construct using com.stupidbeauty.hxlauncher.StartFaceRecognizeReq.newBuilder()
    private Builder() {
      maybeForceBuilderInitialization();
    }

    private Builder(
        com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
      super(parent);
      maybeForceBuilderInitialization();
    }
    private void maybeForceBuilderInitialization() {
      if (com.google.protobuf.GeneratedMessageV3
              .alwaysUseFieldBuilders) {
      }
    }
    @java.lang.Override
    public Builder clear() {
      super.clear();
      maxFaceAmount_ = 0;

      detectMaxFaceAmount_ = 0;

      return this;
    }

    @java.lang.Override
    public com.google.protobuf.Descriptors.Descriptor
        getDescriptorForType() {
      return com.stupidbeauty.hxlauncher.StartFaceRecognizeReqProtos.internal_static_com_stupidbeauty_hxlauncher_StartFaceRecognizeReq_descriptor;
    }

    @java.lang.Override
    public com.stupidbeauty.hxlauncher.StartFaceRecognizeReq getDefaultInstanceForType() {
      return com.stupidbeauty.hxlauncher.StartFaceRecognizeReq.getDefaultInstance();
    }

    @java.lang.Override
    public com.stupidbeauty.hxlauncher.StartFaceRecognizeReq build() {
      com.stupidbeauty.hxlauncher.StartFaceRecognizeReq result = buildPartial();
      if (!result.isInitialized()) {
        throw newUninitializedMessageException(result);
      }
      return result;
    }

    @java.lang.Override
    public com.stupidbeauty.hxlauncher.StartFaceRecognizeReq buildPartial() {
      com.stupidbeauty.hxlauncher.StartFaceRecognizeReq result = new com.stupidbeauty.hxlauncher.StartFaceRecognizeReq(this);
      result.maxFaceAmount_ = maxFaceAmount_;
      result.detectMaxFaceAmount_ = detectMaxFaceAmount_;
      onBuilt();
      return result;
    }

    @java.lang.Override
    public Builder clone() {
      return (Builder) super.clone();
    }
    @java.lang.Override
    public Builder setField(
        com.google.protobuf.Descriptors.FieldDescriptor field,
        java.lang.Object value) {
      return (Builder) super.setField(field, value);
    }
    @java.lang.Override
    public Builder clearField(
        com.google.protobuf.Descriptors.FieldDescriptor field) {
      return (Builder) super.clearField(field);
    }
    @java.lang.Override
    public Builder clearOneof(
        com.google.protobuf.Descriptors.OneofDescriptor oneof) {
      return (Builder) super.clearOneof(oneof);
    }
    @java.lang.Override
    public Builder setRepeatedField(
        com.google.protobuf.Descriptors.FieldDescriptor field,
        int index, java.lang.Object value) {
      return (Builder) super.setRepeatedField(field, index, value);
    }
    @java.lang.Override
    public Builder addRepeatedField(
        com.google.protobuf.Descriptors.FieldDescriptor field,
        java.lang.Object value) {
      return (Builder) super.addRepeatedField(field, value);
    }
    @java.lang.Override
    public Builder mergeFrom(com.google.protobuf.Message other) {
      if (other instanceof com.stupidbeauty.hxlauncher.StartFaceRecognizeReq) {
        return mergeFrom((com.stupidbeauty.hxlauncher.StartFaceRecognizeReq)other);
      } else {
        super.mergeFrom(other);
        return this;
      }
    }

    public Builder mergeFrom(com.stupidbeauty.hxlauncher.StartFaceRecognizeReq other) {
      if (other == com.stupidbeauty.hxlauncher.StartFaceRecognizeReq.getDefaultInstance()) return this;
      if (other.getMaxFaceAmount() != 0) {
        setMaxFaceAmount(other.getMaxFaceAmount());
      }
      if (other.getDetectMaxFaceAmount() != 0) {
        setDetectMaxFaceAmount(other.getDetectMaxFaceAmount());
      }
      this.mergeUnknownFields(other.unknownFields);
      onChanged();
      return this;
    }

    @java.lang.Override
    public final boolean isInitialized() {
      return true;
    }

    @java.lang.Override
    public Builder mergeFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      com.stupidbeauty.hxlauncher.StartFaceRecognizeReq parsedMessage = null;
      try {
        parsedMessage = PARSER.parsePartialFrom(input, extensionRegistry);
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        parsedMessage = (com.stupidbeauty.hxlauncher.StartFaceRecognizeReq) e.getUnfinishedMessage();
        throw e.unwrapIOException();
      } finally {
        if (parsedMessage != null) {
          mergeFrom(parsedMessage);
        }
      }
      return this;
    }

    private int maxFaceAmount_ ;
    /**
     * <pre>
     *最多的人脸个数。
     * </pre>
     *
     * <code>int32 maxFaceAmount = 1;</code>
     */
    public int getMaxFaceAmount() {
      return maxFaceAmount_;
    }
    /**
     * <pre>
     *最多的人脸个数。
     * </pre>
     *
     * <code>int32 maxFaceAmount = 1;</code>
     */
    public Builder setMaxFaceAmount(int value) {
      
      maxFaceAmount_ = value;
      onChanged();
      return this;
    }
    /**
     * <pre>
     *最多的人脸个数。
     * </pre>
     *
     * <code>int32 maxFaceAmount = 1;</code>
     */
    public Builder clearMaxFaceAmount() {
      
      maxFaceAmount_ = 0;
      onChanged();
      return this;
    }

    private int detectMaxFaceAmount_ ;
    /**
     * <pre>
     *最多允许检测到以进行识别的人脸个数。
     * </pre>
     *
     * <code>int32 detectMaxFaceAmount = 2;</code>
     */
    public int getDetectMaxFaceAmount() {
      return detectMaxFaceAmount_;
    }
    /**
     * <pre>
     *最多允许检测到以进行识别的人脸个数。
     * </pre>
     *
     * <code>int32 detectMaxFaceAmount = 2;</code>
     */
    public Builder setDetectMaxFaceAmount(int value) {
      
      detectMaxFaceAmount_ = value;
      onChanged();
      return this;
    }
    /**
     * <pre>
     *最多允许检测到以进行识别的人脸个数。
     * </pre>
     *
     * <code>int32 detectMaxFaceAmount = 2;</code>
     */
    public Builder clearDetectMaxFaceAmount() {
      
      detectMaxFaceAmount_ = 0;
      onChanged();
      return this;
    }
    @java.lang.Override
    public final Builder setUnknownFields(
        final com.google.protobuf.UnknownFieldSet unknownFields) {
      return super.setUnknownFieldsProto3(unknownFields);
    }

    @java.lang.Override
    public final Builder mergeUnknownFields(
        final com.google.protobuf.UnknownFieldSet unknownFields) {
      return super.mergeUnknownFields(unknownFields);
    }


    // @@protoc_insertion_point(builder_scope:com.stupidbeauty.hxlauncher.StartFaceRecognizeReq)
  }

  // @@protoc_insertion_point(class_scope:com.stupidbeauty.hxlauncher.StartFaceRecognizeReq)
  private static final com.stupidbeauty.hxlauncher.StartFaceRecognizeReq DEFAULT_INSTANCE;
  static {
    DEFAULT_INSTANCE = new com.stupidbeauty.hxlauncher.StartFaceRecognizeReq();
  }

  public static com.stupidbeauty.hxlauncher.StartFaceRecognizeReq getDefaultInstance() {
    return DEFAULT_INSTANCE;
  }

  private static final com.google.protobuf.Parser<StartFaceRecognizeReq>
      PARSER = new com.google.protobuf.AbstractParser<StartFaceRecognizeReq>() {
    @java.lang.Override
    public StartFaceRecognizeReq parsePartialFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return new StartFaceRecognizeReq(input, extensionRegistry);
    }
  };

  public static com.google.protobuf.Parser<StartFaceRecognizeReq> parser() {
    return PARSER;
  }

  @java.lang.Override
  public com.google.protobuf.Parser<StartFaceRecognizeReq> getParserForType() {
    return PARSER;
  }

  @java.lang.Override
  public com.stupidbeauty.hxlauncher.StartFaceRecognizeReq getDefaultInstanceForType() {
    return DEFAULT_INSTANCE;
  }

}

