// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: StartFaceRecognizeReq.proto

package com.stupidbeauty.hxlauncher;

public interface StartFaceRecognizeReqOrBuilder extends
    // @@protoc_insertion_point(interface_extends:com.stupidbeauty.hxlauncher.StartFaceRecognizeReq)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <pre>
   *最多的人脸个数。
   * </pre>
   *
   * <code>int32 maxFaceAmount = 1;</code>
   */
  int getMaxFaceAmount();

  /**
   * <pre>
   *最多允许检测到以进行识别的人脸个数。
   * </pre>
   *
   * <code>int32 detectMaxFaceAmount = 2;</code>
   */
  int getDetectMaxFaceAmount();
}
